// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mh-sso-svc/internal/model"
)

func newSysAuditLog(db *gorm.DB, opts ...gen.DOOption) sysAuditLog {
	_sysAuditLog := sysAuditLog{}

	_sysAuditLog.sysAuditLogDo.UseDB(db, opts...)
	_sysAuditLog.sysAuditLogDo.UseModel(&model.SysAuditLog{})

	tableName := _sysAuditLog.sysAuditLogDo.TableName()
	_sysAuditLog.ALL = field.NewAsterisk(tableName)
	_sysAuditLog.ID = field.NewUint64(tableName, "id")
	_sysAuditLog.UserID = field.NewUint64(tableName, "user_id")
	_sysAuditLog.Action = field.NewString(tableName, "action")
	_sysAuditLog.TargetType = field.NewString(tableName, "target_type")
	_sysAuditLog.TargetID = field.NewString(tableName, "target_id")
	_sysAuditLog.Detail = field.NewString(tableName, "detail")
	_sysAuditLog.IP = field.NewString(tableName, "ip")
	_sysAuditLog.RequestID = field.NewString(tableName, "request_id")
	_sysAuditLog.Result = field.NewInt32(tableName, "result")
	_sysAuditLog.ErrorMessage = field.NewString(tableName, "error_message")
	_sysAuditLog.CreateTime = field.NewTime(tableName, "create_time")

	_sysAuditLog.fillFieldMap()

	return _sysAuditLog
}

type sysAuditLog struct {
	sysAuditLogDo

	ALL field.Asterisk
	ID field.Uint64
	UserID field.Uint64 // 操作人ID
	Action field.String // 操作类型
	TargetType field.String // 目标类型
	TargetID field.String // 目标ID
	Detail field.String // 变更明细
	IP field.String // 操作来源IP
	RequestID field.String // 请求追踪ID
	Result field.Int32 // 执行结果
	ErrorMessage field.String // 失败原因
	CreateTime field.Time

	fieldMap map[string]field.Expr
}

func (sysAuditLog sysAuditLog) Table(newTableName string) *sysAuditLog {
	sysAuditLog.sysAuditLogDo.UseTable(newTableName)
	return sysAuditLog.updateTableName(newTableName)
}

func (sysAuditLog sysAuditLog) As(alias string) *sysAuditLog {
	sysAuditLog.sysAuditLogDo.DO = *(sysAuditLog.sysAuditLogDo.As(alias).(*gen.DO))
	return sysAuditLog.updateTableName(alias)
}

func (sysAuditLog *sysAuditLog) updateTableName(table string) *sysAuditLog {
	sysAuditLog.ALL = field.NewAsterisk(table)
	sysAuditLog.ID = field.NewUint64(table, "id")
	sysAuditLog.UserID = field.NewUint64(table, "user_id")
	sysAuditLog.Action = field.NewString(table, "action")
	sysAuditLog.TargetType = field.NewString(table, "target_type")
	sysAuditLog.TargetID = field.NewString(table, "target_id")
	sysAuditLog.Detail = field.NewString(table, "detail")
	sysAuditLog.IP = field.NewString(table, "ip")
	sysAuditLog.RequestID = field.NewString(table, "request_id")
	sysAuditLog.Result = field.NewInt32(table, "result")
	sysAuditLog.ErrorMessage = field.NewString(table, "error_message")
	sysAuditLog.CreateTime = field.NewTime(table, "create_time")

	sysAuditLog.fillFieldMap()

	return sysAuditLog
}

func (sysAuditLog *sysAuditLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := sysAuditLog.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (sysAuditLog *sysAuditLog) fillFieldMap() {
	sysAuditLog.fieldMap = make(map[string]field.Expr, 11)
	sysAuditLog.fieldMap["id"] = sysAuditLog.ID
	sysAuditLog.fieldMap["user_id"] = sysAuditLog.UserID
	sysAuditLog.fieldMap["action"] = sysAuditLog.Action
	sysAuditLog.fieldMap["target_type"] = sysAuditLog.TargetType
	sysAuditLog.fieldMap["target_id"] = sysAuditLog.TargetID
	sysAuditLog.fieldMap["detail"] = sysAuditLog.Detail
	sysAuditLog.fieldMap["ip"] = sysAuditLog.IP
	sysAuditLog.fieldMap["request_id"] = sysAuditLog.RequestID
	sysAuditLog.fieldMap["result"] = sysAuditLog.Result
	sysAuditLog.fieldMap["error_message"] = sysAuditLog.ErrorMessage
	sysAuditLog.fieldMap["create_time"] = sysAuditLog.CreateTime
}

func (sysAuditLog sysAuditLog) clone(db *gorm.DB) sysAuditLog {
	sysAuditLog.sysAuditLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return sysAuditLog
}

func (sysAuditLog sysAuditLog) replaceDB(db *gorm.DB) sysAuditLog {
	sysAuditLog.sysAuditLogDo.ReplaceDB(db)
	return sysAuditLog
}

type sysAuditLogDo struct{ gen.DO }

func (sysAuditLog sysAuditLogDo) Debug() *sysAuditLogDo {
	return sysAuditLog.withDO(sysAuditLog.DO.Debug())
}

func (sysAuditLog sysAuditLogDo) WithContext(ctx context.Context) *sysAuditLogDo {
	return sysAuditLog.withDO(sysAuditLog.DO.WithContext(ctx))
}

func (sysAuditLog sysAuditLogDo) ReadDB() *sysAuditLogDo {
	return sysAuditLog.Clauses(dbresolver.Read)
}

func (sysAuditLog sysAuditLogDo) WriteDB() *sysAuditLogDo {
	return sysAuditLog.Clauses(dbresolver.Write)
}

func (sysAuditLog sysAuditLogDo) Session(config *gorm.Session) *sysAuditLogDo {
	return sysAuditLog.withDO(sysAuditLog.DO.Session(config))
}

func (sysAuditLog sysAuditLogDo) Clauses(conds ...clause.Expression) *sysAuditLogDo {
	return sysAuditLog.withDO(sysAuditLog.DO.Clauses(conds...))
}

func (sysAuditLog sysAuditLogDo) Returning(value interface{}, columns ...string) *sysAuditLogDo {
	return sysAuditLog.withDO(sysAuditLog.DO.Returning(value, columns...))
}

func (sysAuditLog sysAuditLogDo) Not(conds ...gen.Condition) *sysAuditLogDo {
	return sysAuditLog.withDO(sysAuditLog.DO.Not(conds...))
}

func (sysAuditLog sysAuditLogDo) Or(conds ...gen.Condition) *sysAuditLogDo {
	return sysAuditLog.withDO(sysAuditLog.DO.Or(conds...))
}

func (sysAuditLog sysAuditLogDo) Select(conds ...field.Expr) *sysAuditLogDo {
	return sysAuditLog.withDO(sysAuditLog.DO.Select(conds...))
}

func (sysAuditLog sysAuditLogDo) Where(conds ...gen.Condition) *sysAuditLogDo {
	return sysAuditLog.withDO(sysAuditLog.DO.Where(conds...))
}

func (sysAuditLog sysAuditLogDo) Order(conds ...field.Expr) *sysAuditLogDo {
	return sysAuditLog.withDO(sysAuditLog.DO.Order(conds...))
}

func (sysAuditLog sysAuditLogDo) Distinct(cols ...field.Expr) *sysAuditLogDo {
	return sysAuditLog.withDO(sysAuditLog.DO.Distinct(cols...))
}

func (sysAuditLog sysAuditLogDo) Omit(cols ...field.Expr) *sysAuditLogDo {
	return sysAuditLog.withDO(sysAuditLog.DO.Omit(cols...))
}

func (sysAuditLog sysAuditLogDo) Join(table schema.Tabler, on ...field.Expr) *sysAuditLogDo {
	return sysAuditLog.withDO(sysAuditLog.DO.Join(table, on...))
}

func (sysAuditLog sysAuditLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) *sysAuditLogDo {
	return sysAuditLog.withDO(sysAuditLog.DO.LeftJoin(table, on...))
}

func (sysAuditLog sysAuditLogDo) RightJoin(table schema.Tabler, on ...field.Expr) *sysAuditLogDo {
	return sysAuditLog.withDO(sysAuditLog.DO.RightJoin(table, on...))
}

func (sysAuditLog sysAuditLogDo) Group(cols ...field.Expr) *sysAuditLogDo {
	return sysAuditLog.withDO(sysAuditLog.DO.Group(cols...))
}

func (sysAuditLog sysAuditLogDo) Having(conds ...gen.Condition) *sysAuditLogDo {
	return sysAuditLog.withDO(sysAuditLog.DO.Having(conds...))
}

func (sysAuditLog sysAuditLogDo) Limit(limit int) *sysAuditLogDo {
	return sysAuditLog.withDO(sysAuditLog.DO.Limit(limit))
}

func (sysAuditLog sysAuditLogDo) Offset(offset int) *sysAuditLogDo {
	return sysAuditLog.withDO(sysAuditLog.DO.Offset(offset))
}

func (sysAuditLog sysAuditLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *sysAuditLogDo {
	return sysAuditLog.withDO(sysAuditLog.DO.Scopes(funcs...))
}

func (sysAuditLog sysAuditLogDo) Unscoped() *sysAuditLogDo {
	return sysAuditLog.withDO(sysAuditLog.DO.Unscoped())
}

func (sysAuditLog sysAuditLogDo) Create(values ...*model.SysAuditLog) error {
	if len(values) == 0 {
		return nil
	}
	return sysAuditLog.DO.Create(values)
}

func (sysAuditLog sysAuditLogDo) CreateInBatches(values []*model.SysAuditLog, batchSize int) error {
	return sysAuditLog.DO.CreateInBatches(values, batchSize)
}

func (sysAuditLog sysAuditLogDo) Save(values ...*model.SysAuditLog) error {
	if len(values) == 0 {
		return nil
	}
	return sysAuditLog.DO.Save(values)
}

func (sysAuditLog sysAuditLogDo) First() (*model.SysAuditLog, error) {
	if result, err := sysAuditLog.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysAuditLog), nil
	}
}

func (sysAuditLog sysAuditLogDo) Take() (*model.SysAuditLog, error) {
	if result, err := sysAuditLog.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysAuditLog), nil
	}
}

func (sysAuditLog sysAuditLogDo) Last() (*model.SysAuditLog, error) {
	if result, err := sysAuditLog.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysAuditLog), nil
	}
}

func (sysAuditLog sysAuditLogDo) Find() ([]*model.SysAuditLog, error) {
	result, err := sysAuditLog.DO.Find()
	return result.([]*model.SysAuditLog), err
}

func (sysAuditLog sysAuditLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysAuditLog, err error) {
	buf := make([]*model.SysAuditLog, 0, batchSize)
	err = sysAuditLog.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (sysAuditLog sysAuditLogDo) FindInBatches(result *[]*model.SysAuditLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return sysAuditLog.DO.FindInBatches(result, batchSize, fc)
}

func (sysAuditLog sysAuditLogDo) Attrs(attrs ...field.AssignExpr) *sysAuditLogDo {
	return sysAuditLog.withDO(sysAuditLog.DO.Attrs(attrs...))
}

func (sysAuditLog sysAuditLogDo) Assign(attrs ...field.AssignExpr) *sysAuditLogDo {
	return sysAuditLog.withDO(sysAuditLog.DO.Assign(attrs...))
}

func (sysAuditLog sysAuditLogDo) Joins(fields ...field.RelationField) *sysAuditLogDo {
	for _, _f := range fields {
		sysAuditLog = *sysAuditLog.withDO(sysAuditLog.DO.Joins(_f))
	}
	return &sysAuditLog
}

func (sysAuditLog sysAuditLogDo) Preload(fields ...field.RelationField) *sysAuditLogDo {
	for _, _f := range fields {
		sysAuditLog = *sysAuditLog.withDO(sysAuditLog.DO.Preload(_f))
	}
	return &sysAuditLog
}

func (sysAuditLog sysAuditLogDo) FirstOrInit() (*model.SysAuditLog, error) {
	if result, err := sysAuditLog.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysAuditLog), nil
	}
}

func (sysAuditLog sysAuditLogDo) FirstOrCreate() (*model.SysAuditLog, error) {
	if result, err := sysAuditLog.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysAuditLog), nil
	}
}

func (sysAuditLog sysAuditLogDo) FindByPage(offset int, limit int) (result []*model.SysAuditLog, count int64, err error) {
	result, err = sysAuditLog.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = sysAuditLog.Offset(-1).Limit(-1).Count()
	return
}

func (sysAuditLog sysAuditLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = sysAuditLog.Count()
	if err != nil {
		return
	}

	err = sysAuditLog.Offset(offset).Limit(limit).Scan(result)
	return
}

func (sysAuditLog sysAuditLogDo) Scan(result interface{}) (err error) {
	return sysAuditLog.DO.Scan(result)
}

func (sysAuditLog sysAuditLogDo) Delete(models ...*model.SysAuditLog) (result gen.ResultInfo, err error) {
	return sysAuditLog.DO.Delete(models)
}

func (sysAuditLog *sysAuditLogDo) withDO(do gen.Dao) *sysAuditLogDo {
	sysAuditLog.DO = *do.(*gen.DO)
	return sysAuditLog
}
