// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mh-sso-svc/internal/model"
)

func newSysUserRole(db *gorm.DB, opts ...gen.DOOption) sysUserRole {
	_sysUserRole := sysUserRole{}

	_sysUserRole.sysUserRoleDo.UseDB(db, opts...)
	_sysUserRole.sysUserRoleDo.UseModel(&model.SysUserRole{})

	tableName := _sysUserRole.sysUserRoleDo.TableName()
	_sysUserRole.ALL = field.NewAsterisk(tableName)
	_sysUserRole.ID = field.NewUint64(tableName, "id")
	_sysUserRole.UserID = field.NewUint64(tableName, "user_id")
	_sysUserRole.RoleID = field.NewUint64(tableName, "role_id")
	_sysUserRole.CreateTime = field.NewTime(tableName, "create_time")

	_sysUserRole.fillFieldMap()

	return _sysUserRole
}

type sysUserRole struct {
	sysUserRoleDo

	ALL field.Asterisk
	ID field.Uint64
	UserID field.Uint64 // 用户ID
	RoleID field.Uint64 // 角色ID
	CreateTime field.Time

	fieldMap map[string]field.Expr
}

func (sysUserRole sysUserRole) Table(newTableName string) *sysUserRole {
	sysUserRole.sysUserRoleDo.UseTable(newTableName)
	return sysUserRole.updateTableName(newTableName)
}

func (sysUserRole sysUserRole) As(alias string) *sysUserRole {
	sysUserRole.sysUserRoleDo.DO = *(sysUserRole.sysUserRoleDo.As(alias).(*gen.DO))
	return sysUserRole.updateTableName(alias)
}

func (sysUserRole *sysUserRole) updateTableName(table string) *sysUserRole {
	sysUserRole.ALL = field.NewAsterisk(table)
	sysUserRole.ID = field.NewUint64(table, "id")
	sysUserRole.UserID = field.NewUint64(table, "user_id")
	sysUserRole.RoleID = field.NewUint64(table, "role_id")
	sysUserRole.CreateTime = field.NewTime(table, "create_time")

	sysUserRole.fillFieldMap()

	return sysUserRole
}

func (sysUserRole *sysUserRole) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := sysUserRole.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (sysUserRole *sysUserRole) fillFieldMap() {
	sysUserRole.fieldMap = make(map[string]field.Expr, 4)
	sysUserRole.fieldMap["id"] = sysUserRole.ID
	sysUserRole.fieldMap["user_id"] = sysUserRole.UserID
	sysUserRole.fieldMap["role_id"] = sysUserRole.RoleID
	sysUserRole.fieldMap["create_time"] = sysUserRole.CreateTime
}

func (sysUserRole sysUserRole) clone(db *gorm.DB) sysUserRole {
	sysUserRole.sysUserRoleDo.ReplaceConnPool(db.Statement.ConnPool)
	return sysUserRole
}

func (sysUserRole sysUserRole) replaceDB(db *gorm.DB) sysUserRole {
	sysUserRole.sysUserRoleDo.ReplaceDB(db)
	return sysUserRole
}

type sysUserRoleDo struct{ gen.DO }

func (sysUserRole sysUserRoleDo) Debug() *sysUserRoleDo {
	return sysUserRole.withDO(sysUserRole.DO.Debug())
}

func (sysUserRole sysUserRoleDo) WithContext(ctx context.Context) *sysUserRoleDo {
	return sysUserRole.withDO(sysUserRole.DO.WithContext(ctx))
}

func (sysUserRole sysUserRoleDo) ReadDB() *sysUserRoleDo {
	return sysUserRole.Clauses(dbresolver.Read)
}

func (sysUserRole sysUserRoleDo) WriteDB() *sysUserRoleDo {
	return sysUserRole.Clauses(dbresolver.Write)
}

func (sysUserRole sysUserRoleDo) Session(config *gorm.Session) *sysUserRoleDo {
	return sysUserRole.withDO(sysUserRole.DO.Session(config))
}

func (sysUserRole sysUserRoleDo) Clauses(conds ...clause.Expression) *sysUserRoleDo {
	return sysUserRole.withDO(sysUserRole.DO.Clauses(conds...))
}

func (sysUserRole sysUserRoleDo) Returning(value interface{}, columns ...string) *sysUserRoleDo {
	return sysUserRole.withDO(sysUserRole.DO.Returning(value, columns...))
}

func (sysUserRole sysUserRoleDo) Not(conds ...gen.Condition) *sysUserRoleDo {
	return sysUserRole.withDO(sysUserRole.DO.Not(conds...))
}

func (sysUserRole sysUserRoleDo) Or(conds ...gen.Condition) *sysUserRoleDo {
	return sysUserRole.withDO(sysUserRole.DO.Or(conds...))
}

func (sysUserRole sysUserRoleDo) Select(conds ...field.Expr) *sysUserRoleDo {
	return sysUserRole.withDO(sysUserRole.DO.Select(conds...))
}

func (sysUserRole sysUserRoleDo) Where(conds ...gen.Condition) *sysUserRoleDo {
	return sysUserRole.withDO(sysUserRole.DO.Where(conds...))
}

func (sysUserRole sysUserRoleDo) Order(conds ...field.Expr) *sysUserRoleDo {
	return sysUserRole.withDO(sysUserRole.DO.Order(conds...))
}

func (sysUserRole sysUserRoleDo) Distinct(cols ...field.Expr) *sysUserRoleDo {
	return sysUserRole.withDO(sysUserRole.DO.Distinct(cols...))
}

func (sysUserRole sysUserRoleDo) Omit(cols ...field.Expr) *sysUserRoleDo {
	return sysUserRole.withDO(sysUserRole.DO.Omit(cols...))
}

func (sysUserRole sysUserRoleDo) Join(table schema.Tabler, on ...field.Expr) *sysUserRoleDo {
	return sysUserRole.withDO(sysUserRole.DO.Join(table, on...))
}

func (sysUserRole sysUserRoleDo) LeftJoin(table schema.Tabler, on ...field.Expr) *sysUserRoleDo {
	return sysUserRole.withDO(sysUserRole.DO.LeftJoin(table, on...))
}

func (sysUserRole sysUserRoleDo) RightJoin(table schema.Tabler, on ...field.Expr) *sysUserRoleDo {
	return sysUserRole.withDO(sysUserRole.DO.RightJoin(table, on...))
}

func (sysUserRole sysUserRoleDo) Group(cols ...field.Expr) *sysUserRoleDo {
	return sysUserRole.withDO(sysUserRole.DO.Group(cols...))
}

func (sysUserRole sysUserRoleDo) Having(conds ...gen.Condition) *sysUserRoleDo {
	return sysUserRole.withDO(sysUserRole.DO.Having(conds...))
}

func (sysUserRole sysUserRoleDo) Limit(limit int) *sysUserRoleDo {
	return sysUserRole.withDO(sysUserRole.DO.Limit(limit))
}

func (sysUserRole sysUserRoleDo) Offset(offset int) *sysUserRoleDo {
	return sysUserRole.withDO(sysUserRole.DO.Offset(offset))
}

func (sysUserRole sysUserRoleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *sysUserRoleDo {
	return sysUserRole.withDO(sysUserRole.DO.Scopes(funcs...))
}

func (sysUserRole sysUserRoleDo) Unscoped() *sysUserRoleDo {
	return sysUserRole.withDO(sysUserRole.DO.Unscoped())
}

func (sysUserRole sysUserRoleDo) Create(values ...*model.SysUserRole) error {
	if len(values) == 0 {
		return nil
	}
	return sysUserRole.DO.Create(values)
}

func (sysUserRole sysUserRoleDo) CreateInBatches(values []*model.SysUserRole, batchSize int) error {
	return sysUserRole.DO.CreateInBatches(values, batchSize)
}

func (sysUserRole sysUserRoleDo) Save(values ...*model.SysUserRole) error {
	if len(values) == 0 {
		return nil
	}
	return sysUserRole.DO.Save(values)
}

func (sysUserRole sysUserRoleDo) First() (*model.SysUserRole, error) {
	if result, err := sysUserRole.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUserRole), nil
	}
}

func (sysUserRole sysUserRoleDo) Take() (*model.SysUserRole, error) {
	if result, err := sysUserRole.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUserRole), nil
	}
}

func (sysUserRole sysUserRoleDo) Last() (*model.SysUserRole, error) {
	if result, err := sysUserRole.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUserRole), nil
	}
}

func (sysUserRole sysUserRoleDo) Find() ([]*model.SysUserRole, error) {
	result, err := sysUserRole.DO.Find()
	return result.([]*model.SysUserRole), err
}

func (sysUserRole sysUserRoleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysUserRole, err error) {
	buf := make([]*model.SysUserRole, 0, batchSize)
	err = sysUserRole.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (sysUserRole sysUserRoleDo) FindInBatches(result *[]*model.SysUserRole, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return sysUserRole.DO.FindInBatches(result, batchSize, fc)
}

func (sysUserRole sysUserRoleDo) Attrs(attrs ...field.AssignExpr) *sysUserRoleDo {
	return sysUserRole.withDO(sysUserRole.DO.Attrs(attrs...))
}

func (sysUserRole sysUserRoleDo) Assign(attrs ...field.AssignExpr) *sysUserRoleDo {
	return sysUserRole.withDO(sysUserRole.DO.Assign(attrs...))
}

func (sysUserRole sysUserRoleDo) Joins(fields ...field.RelationField) *sysUserRoleDo {
	for _, _f := range fields {
		sysUserRole = *sysUserRole.withDO(sysUserRole.DO.Joins(_f))
	}
	return &sysUserRole
}

func (sysUserRole sysUserRoleDo) Preload(fields ...field.RelationField) *sysUserRoleDo {
	for _, _f := range fields {
		sysUserRole = *sysUserRole.withDO(sysUserRole.DO.Preload(_f))
	}
	return &sysUserRole
}

func (sysUserRole sysUserRoleDo) FirstOrInit() (*model.SysUserRole, error) {
	if result, err := sysUserRole.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUserRole), nil
	}
}

func (sysUserRole sysUserRoleDo) FirstOrCreate() (*model.SysUserRole, error) {
	if result, err := sysUserRole.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUserRole), nil
	}
}

func (sysUserRole sysUserRoleDo) FindByPage(offset int, limit int) (result []*model.SysUserRole, count int64, err error) {
	result, err = sysUserRole.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = sysUserRole.Offset(-1).Limit(-1).Count()
	return
}

func (sysUserRole sysUserRoleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = sysUserRole.Count()
	if err != nil {
		return
	}

	err = sysUserRole.Offset(offset).Limit(limit).Scan(result)
	return
}

func (sysUserRole sysUserRoleDo) Scan(result interface{}) (err error) {
	return sysUserRole.DO.Scan(result)
}

func (sysUserRole sysUserRoleDo) Delete(models ...*model.SysUserRole) (result gen.ResultInfo, err error) {
	return sysUserRole.DO.Delete(models)
}

func (sysUserRole *sysUserRoleDo) withDO(do gen.Dao) *sysUserRoleDo {
	sysUserRole.DO = *do.(*gen.DO)
	return sysUserRole
}
