// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mh-sso-svc/internal/model"
)

func newSysPlatform(db *gorm.DB, opts ...gen.DOOption) sysPlatform {
	_sysPlatform := sysPlatform{}

	_sysPlatform.sysPlatformDo.UseDB(db, opts...)
	_sysPlatform.sysPlatformDo.UseModel(&model.SysPlatform{})

	tableName := _sysPlatform.sysPlatformDo.TableName()
	_sysPlatform.ALL = field.NewAsterisk(tableName)
	_sysPlatform.ID = field.NewUint64(tableName, "id")
	_sysPlatform.Name = field.NewString(tableName, "name")
	_sysPlatform.Code = field.NewString(tableName, "code")
	_sysPlatform.CreateTime = field.NewTime(tableName, "create_time")
	_sysPlatform.UpdateTime = field.NewTime(tableName, "update_time")

	_sysPlatform.fillFieldMap()

	return _sysPlatform
}

type sysPlatform struct {
	sysPlatformDo

	ALL field.Asterisk
	ID field.Uint64
	Name field.String // 平台名称
	Code field.String // 平台编码
	CreateTime field.Time
	UpdateTime field.Time

	fieldMap map[string]field.Expr
}

func (sysPlatform sysPlatform) Table(newTableName string) *sysPlatform {
	sysPlatform.sysPlatformDo.UseTable(newTableName)
	return sysPlatform.updateTableName(newTableName)
}

func (sysPlatform sysPlatform) As(alias string) *sysPlatform {
	sysPlatform.sysPlatformDo.DO = *(sysPlatform.sysPlatformDo.As(alias).(*gen.DO))
	return sysPlatform.updateTableName(alias)
}

func (sysPlatform *sysPlatform) updateTableName(table string) *sysPlatform {
	sysPlatform.ALL = field.NewAsterisk(table)
	sysPlatform.ID = field.NewUint64(table, "id")
	sysPlatform.Name = field.NewString(table, "name")
	sysPlatform.Code = field.NewString(table, "code")
	sysPlatform.CreateTime = field.NewTime(table, "create_time")
	sysPlatform.UpdateTime = field.NewTime(table, "update_time")

	sysPlatform.fillFieldMap()

	return sysPlatform
}

func (sysPlatform *sysPlatform) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := sysPlatform.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (sysPlatform *sysPlatform) fillFieldMap() {
	sysPlatform.fieldMap = make(map[string]field.Expr, 5)
	sysPlatform.fieldMap["id"] = sysPlatform.ID
	sysPlatform.fieldMap["name"] = sysPlatform.Name
	sysPlatform.fieldMap["code"] = sysPlatform.Code
	sysPlatform.fieldMap["create_time"] = sysPlatform.CreateTime
	sysPlatform.fieldMap["update_time"] = sysPlatform.UpdateTime
}

func (sysPlatform sysPlatform) clone(db *gorm.DB) sysPlatform {
	sysPlatform.sysPlatformDo.ReplaceConnPool(db.Statement.ConnPool)
	return sysPlatform
}

func (sysPlatform sysPlatform) replaceDB(db *gorm.DB) sysPlatform {
	sysPlatform.sysPlatformDo.ReplaceDB(db)
	return sysPlatform
}

type sysPlatformDo struct{ gen.DO }

func (sysPlatform sysPlatformDo) Debug() *sysPlatformDo {
	return sysPlatform.withDO(sysPlatform.DO.Debug())
}

func (sysPlatform sysPlatformDo) WithContext(ctx context.Context) *sysPlatformDo {
	return sysPlatform.withDO(sysPlatform.DO.WithContext(ctx))
}

func (sysPlatform sysPlatformDo) ReadDB() *sysPlatformDo {
	return sysPlatform.Clauses(dbresolver.Read)
}

func (sysPlatform sysPlatformDo) WriteDB() *sysPlatformDo {
	return sysPlatform.Clauses(dbresolver.Write)
}

func (sysPlatform sysPlatformDo) Session(config *gorm.Session) *sysPlatformDo {
	return sysPlatform.withDO(sysPlatform.DO.Session(config))
}

func (sysPlatform sysPlatformDo) Clauses(conds ...clause.Expression) *sysPlatformDo {
	return sysPlatform.withDO(sysPlatform.DO.Clauses(conds...))
}

func (sysPlatform sysPlatformDo) Returning(value interface{}, columns ...string) *sysPlatformDo {
	return sysPlatform.withDO(sysPlatform.DO.Returning(value, columns...))
}

func (sysPlatform sysPlatformDo) Not(conds ...gen.Condition) *sysPlatformDo {
	return sysPlatform.withDO(sysPlatform.DO.Not(conds...))
}

func (sysPlatform sysPlatformDo) Or(conds ...gen.Condition) *sysPlatformDo {
	return sysPlatform.withDO(sysPlatform.DO.Or(conds...))
}

func (sysPlatform sysPlatformDo) Select(conds ...field.Expr) *sysPlatformDo {
	return sysPlatform.withDO(sysPlatform.DO.Select(conds...))
}

func (sysPlatform sysPlatformDo) Where(conds ...gen.Condition) *sysPlatformDo {
	return sysPlatform.withDO(sysPlatform.DO.Where(conds...))
}

func (sysPlatform sysPlatformDo) Order(conds ...field.Expr) *sysPlatformDo {
	return sysPlatform.withDO(sysPlatform.DO.Order(conds...))
}

func (sysPlatform sysPlatformDo) Distinct(cols ...field.Expr) *sysPlatformDo {
	return sysPlatform.withDO(sysPlatform.DO.Distinct(cols...))
}

func (sysPlatform sysPlatformDo) Omit(cols ...field.Expr) *sysPlatformDo {
	return sysPlatform.withDO(sysPlatform.DO.Omit(cols...))
}

func (sysPlatform sysPlatformDo) Join(table schema.Tabler, on ...field.Expr) *sysPlatformDo {
	return sysPlatform.withDO(sysPlatform.DO.Join(table, on...))
}

func (sysPlatform sysPlatformDo) LeftJoin(table schema.Tabler, on ...field.Expr) *sysPlatformDo {
	return sysPlatform.withDO(sysPlatform.DO.LeftJoin(table, on...))
}

func (sysPlatform sysPlatformDo) RightJoin(table schema.Tabler, on ...field.Expr) *sysPlatformDo {
	return sysPlatform.withDO(sysPlatform.DO.RightJoin(table, on...))
}

func (sysPlatform sysPlatformDo) Group(cols ...field.Expr) *sysPlatformDo {
	return sysPlatform.withDO(sysPlatform.DO.Group(cols...))
}

func (sysPlatform sysPlatformDo) Having(conds ...gen.Condition) *sysPlatformDo {
	return sysPlatform.withDO(sysPlatform.DO.Having(conds...))
}

func (sysPlatform sysPlatformDo) Limit(limit int) *sysPlatformDo {
	return sysPlatform.withDO(sysPlatform.DO.Limit(limit))
}

func (sysPlatform sysPlatformDo) Offset(offset int) *sysPlatformDo {
	return sysPlatform.withDO(sysPlatform.DO.Offset(offset))
}

func (sysPlatform sysPlatformDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *sysPlatformDo {
	return sysPlatform.withDO(sysPlatform.DO.Scopes(funcs...))
}

func (sysPlatform sysPlatformDo) Unscoped() *sysPlatformDo {
	return sysPlatform.withDO(sysPlatform.DO.Unscoped())
}

func (sysPlatform sysPlatformDo) Create(values ...*model.SysPlatform) error {
	if len(values) == 0 {
		return nil
	}
	return sysPlatform.DO.Create(values)
}

func (sysPlatform sysPlatformDo) CreateInBatches(values []*model.SysPlatform, batchSize int) error {
	return sysPlatform.DO.CreateInBatches(values, batchSize)
}

func (sysPlatform sysPlatformDo) Save(values ...*model.SysPlatform) error {
	if len(values) == 0 {
		return nil
	}
	return sysPlatform.DO.Save(values)
}

func (sysPlatform sysPlatformDo) First() (*model.SysPlatform, error) {
	if result, err := sysPlatform.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysPlatform), nil
	}
}

func (sysPlatform sysPlatformDo) Take() (*model.SysPlatform, error) {
	if result, err := sysPlatform.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysPlatform), nil
	}
}

func (sysPlatform sysPlatformDo) Last() (*model.SysPlatform, error) {
	if result, err := sysPlatform.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysPlatform), nil
	}
}

func (sysPlatform sysPlatformDo) Find() ([]*model.SysPlatform, error) {
	result, err := sysPlatform.DO.Find()
	return result.([]*model.SysPlatform), err
}

func (sysPlatform sysPlatformDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysPlatform, err error) {
	buf := make([]*model.SysPlatform, 0, batchSize)
	err = sysPlatform.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (sysPlatform sysPlatformDo) FindInBatches(result *[]*model.SysPlatform, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return sysPlatform.DO.FindInBatches(result, batchSize, fc)
}

func (sysPlatform sysPlatformDo) Attrs(attrs ...field.AssignExpr) *sysPlatformDo {
	return sysPlatform.withDO(sysPlatform.DO.Attrs(attrs...))
}

func (sysPlatform sysPlatformDo) Assign(attrs ...field.AssignExpr) *sysPlatformDo {
	return sysPlatform.withDO(sysPlatform.DO.Assign(attrs...))
}

func (sysPlatform sysPlatformDo) Joins(fields ...field.RelationField) *sysPlatformDo {
	for _, _f := range fields {
		sysPlatform = *sysPlatform.withDO(sysPlatform.DO.Joins(_f))
	}
	return &sysPlatform
}

func (sysPlatform sysPlatformDo) Preload(fields ...field.RelationField) *sysPlatformDo {
	for _, _f := range fields {
		sysPlatform = *sysPlatform.withDO(sysPlatform.DO.Preload(_f))
	}
	return &sysPlatform
}

func (sysPlatform sysPlatformDo) FirstOrInit() (*model.SysPlatform, error) {
	if result, err := sysPlatform.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysPlatform), nil
	}
}

func (sysPlatform sysPlatformDo) FirstOrCreate() (*model.SysPlatform, error) {
	if result, err := sysPlatform.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysPlatform), nil
	}
}

func (sysPlatform sysPlatformDo) FindByPage(offset int, limit int) (result []*model.SysPlatform, count int64, err error) {
	result, err = sysPlatform.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = sysPlatform.Offset(-1).Limit(-1).Count()
	return
}

func (sysPlatform sysPlatformDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = sysPlatform.Count()
	if err != nil {
		return
	}

	err = sysPlatform.Offset(offset).Limit(limit).Scan(result)
	return
}

func (sysPlatform sysPlatformDo) Scan(result interface{}) (err error) {
	return sysPlatform.DO.Scan(result)
}

func (sysPlatform sysPlatformDo) Delete(models ...*model.SysPlatform) (result gen.ResultInfo, err error) {
	return sysPlatform.DO.Delete(models)
}

func (sysPlatform *sysPlatformDo) withDO(do gen.Dao) *sysPlatformDo {
	sysPlatform.DO = *do.(*gen.DO)
	return sysPlatform
}
