// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mh-sso-svc/internal/model"
)

func newSysPermission(db *gorm.DB, opts ...gen.DOOption) sysPermission {
	_sysPermission := sysPermission{}

	_sysPermission.sysPermissionDo.UseDB(db, opts...)
	_sysPermission.sysPermissionDo.UseModel(&model.SysPermission{})

	tableName := _sysPermission.sysPermissionDo.TableName()
	_sysPermission.ALL = field.NewAsterisk(tableName)
	_sysPermission.ID = field.NewUint64(tableName, "id")
	_sysPermission.PlatformID = field.NewUint64(tableName, "platform_id")
	_sysPermission.Code = field.NewString(tableName, "code")
	_sysPermission.Name = field.NewString(tableName, "name")
	_sysPermission.Type = field.NewInt32(tableName, "type")
	_sysPermission.ParentID = field.NewUint64(tableName, "parent_id")
	_sysPermission.Sort = field.NewInt32(tableName, "sort")
	_sysPermission.Status = field.NewInt32(tableName, "status")
	_sysPermission.CreateTime = field.NewTime(tableName, "create_time")
	_sysPermission.UpdateTime = field.NewTime(tableName, "update_time")

	_sysPermission.fillFieldMap()

	return _sysPermission
}

type sysPermission struct {
	sysPermissionDo

	ALL field.Asterisk
	ID field.Uint64
	PlatformID field.Uint64 // 所属平台ID
	Code field.String // 权限编码
	Name field.String // 权限名称
	Type field.Int32 // 类型
	ParentID field.Uint64 // 父权限ID
	Sort field.Int32 // 同级排序
	Status field.Int32 // 状态
	CreateTime field.Time
	UpdateTime field.Time

	fieldMap map[string]field.Expr
}

func (sysPermission sysPermission) Table(newTableName string) *sysPermission {
	sysPermission.sysPermissionDo.UseTable(newTableName)
	return sysPermission.updateTableName(newTableName)
}

func (sysPermission sysPermission) As(alias string) *sysPermission {
	sysPermission.sysPermissionDo.DO = *(sysPermission.sysPermissionDo.As(alias).(*gen.DO))
	return sysPermission.updateTableName(alias)
}

func (sysPermission *sysPermission) updateTableName(table string) *sysPermission {
	sysPermission.ALL = field.NewAsterisk(table)
	sysPermission.ID = field.NewUint64(table, "id")
	sysPermission.PlatformID = field.NewUint64(table, "platform_id")
	sysPermission.Code = field.NewString(table, "code")
	sysPermission.Name = field.NewString(table, "name")
	sysPermission.Type = field.NewInt32(table, "type")
	sysPermission.ParentID = field.NewUint64(table, "parent_id")
	sysPermission.Sort = field.NewInt32(table, "sort")
	sysPermission.Status = field.NewInt32(table, "status")
	sysPermission.CreateTime = field.NewTime(table, "create_time")
	sysPermission.UpdateTime = field.NewTime(table, "update_time")

	sysPermission.fillFieldMap()

	return sysPermission
}

func (sysPermission *sysPermission) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := sysPermission.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (sysPermission *sysPermission) fillFieldMap() {
	sysPermission.fieldMap = make(map[string]field.Expr, 10)
	sysPermission.fieldMap["id"] = sysPermission.ID
	sysPermission.fieldMap["platform_id"] = sysPermission.PlatformID
	sysPermission.fieldMap["code"] = sysPermission.Code
	sysPermission.fieldMap["name"] = sysPermission.Name
	sysPermission.fieldMap["type"] = sysPermission.Type
	sysPermission.fieldMap["parent_id"] = sysPermission.ParentID
	sysPermission.fieldMap["sort"] = sysPermission.Sort
	sysPermission.fieldMap["status"] = sysPermission.Status
	sysPermission.fieldMap["create_time"] = sysPermission.CreateTime
	sysPermission.fieldMap["update_time"] = sysPermission.UpdateTime
}

func (sysPermission sysPermission) clone(db *gorm.DB) sysPermission {
	sysPermission.sysPermissionDo.ReplaceConnPool(db.Statement.ConnPool)
	return sysPermission
}

func (sysPermission sysPermission) replaceDB(db *gorm.DB) sysPermission {
	sysPermission.sysPermissionDo.ReplaceDB(db)
	return sysPermission
}

type sysPermissionDo struct{ gen.DO }

func (sysPermission sysPermissionDo) Debug() *sysPermissionDo {
	return sysPermission.withDO(sysPermission.DO.Debug())
}

func (sysPermission sysPermissionDo) WithContext(ctx context.Context) *sysPermissionDo {
	return sysPermission.withDO(sysPermission.DO.WithContext(ctx))
}

func (sysPermission sysPermissionDo) ReadDB() *sysPermissionDo {
	return sysPermission.Clauses(dbresolver.Read)
}

func (sysPermission sysPermissionDo) WriteDB() *sysPermissionDo {
	return sysPermission.Clauses(dbresolver.Write)
}

func (sysPermission sysPermissionDo) Session(config *gorm.Session) *sysPermissionDo {
	return sysPermission.withDO(sysPermission.DO.Session(config))
}

func (sysPermission sysPermissionDo) Clauses(conds ...clause.Expression) *sysPermissionDo {
	return sysPermission.withDO(sysPermission.DO.Clauses(conds...))
}

func (sysPermission sysPermissionDo) Returning(value interface{}, columns ...string) *sysPermissionDo {
	return sysPermission.withDO(sysPermission.DO.Returning(value, columns...))
}

func (sysPermission sysPermissionDo) Not(conds ...gen.Condition) *sysPermissionDo {
	return sysPermission.withDO(sysPermission.DO.Not(conds...))
}

func (sysPermission sysPermissionDo) Or(conds ...gen.Condition) *sysPermissionDo {
	return sysPermission.withDO(sysPermission.DO.Or(conds...))
}

func (sysPermission sysPermissionDo) Select(conds ...field.Expr) *sysPermissionDo {
	return sysPermission.withDO(sysPermission.DO.Select(conds...))
}

func (sysPermission sysPermissionDo) Where(conds ...gen.Condition) *sysPermissionDo {
	return sysPermission.withDO(sysPermission.DO.Where(conds...))
}

func (sysPermission sysPermissionDo) Order(conds ...field.Expr) *sysPermissionDo {
	return sysPermission.withDO(sysPermission.DO.Order(conds...))
}

func (sysPermission sysPermissionDo) Distinct(cols ...field.Expr) *sysPermissionDo {
	return sysPermission.withDO(sysPermission.DO.Distinct(cols...))
}

func (sysPermission sysPermissionDo) Omit(cols ...field.Expr) *sysPermissionDo {
	return sysPermission.withDO(sysPermission.DO.Omit(cols...))
}

func (sysPermission sysPermissionDo) Join(table schema.Tabler, on ...field.Expr) *sysPermissionDo {
	return sysPermission.withDO(sysPermission.DO.Join(table, on...))
}

func (sysPermission sysPermissionDo) LeftJoin(table schema.Tabler, on ...field.Expr) *sysPermissionDo {
	return sysPermission.withDO(sysPermission.DO.LeftJoin(table, on...))
}

func (sysPermission sysPermissionDo) RightJoin(table schema.Tabler, on ...field.Expr) *sysPermissionDo {
	return sysPermission.withDO(sysPermission.DO.RightJoin(table, on...))
}

func (sysPermission sysPermissionDo) Group(cols ...field.Expr) *sysPermissionDo {
	return sysPermission.withDO(sysPermission.DO.Group(cols...))
}

func (sysPermission sysPermissionDo) Having(conds ...gen.Condition) *sysPermissionDo {
	return sysPermission.withDO(sysPermission.DO.Having(conds...))
}

func (sysPermission sysPermissionDo) Limit(limit int) *sysPermissionDo {
	return sysPermission.withDO(sysPermission.DO.Limit(limit))
}

func (sysPermission sysPermissionDo) Offset(offset int) *sysPermissionDo {
	return sysPermission.withDO(sysPermission.DO.Offset(offset))
}

func (sysPermission sysPermissionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *sysPermissionDo {
	return sysPermission.withDO(sysPermission.DO.Scopes(funcs...))
}

func (sysPermission sysPermissionDo) Unscoped() *sysPermissionDo {
	return sysPermission.withDO(sysPermission.DO.Unscoped())
}

func (sysPermission sysPermissionDo) Create(values ...*model.SysPermission) error {
	if len(values) == 0 {
		return nil
	}
	return sysPermission.DO.Create(values)
}

func (sysPermission sysPermissionDo) CreateInBatches(values []*model.SysPermission, batchSize int) error {
	return sysPermission.DO.CreateInBatches(values, batchSize)
}

func (sysPermission sysPermissionDo) Save(values ...*model.SysPermission) error {
	if len(values) == 0 {
		return nil
	}
	return sysPermission.DO.Save(values)
}

func (sysPermission sysPermissionDo) First() (*model.SysPermission, error) {
	if result, err := sysPermission.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysPermission), nil
	}
}

func (sysPermission sysPermissionDo) Take() (*model.SysPermission, error) {
	if result, err := sysPermission.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysPermission), nil
	}
}

func (sysPermission sysPermissionDo) Last() (*model.SysPermission, error) {
	if result, err := sysPermission.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysPermission), nil
	}
}

func (sysPermission sysPermissionDo) Find() ([]*model.SysPermission, error) {
	result, err := sysPermission.DO.Find()
	return result.([]*model.SysPermission), err
}

func (sysPermission sysPermissionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysPermission, err error) {
	buf := make([]*model.SysPermission, 0, batchSize)
	err = sysPermission.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (sysPermission sysPermissionDo) FindInBatches(result *[]*model.SysPermission, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return sysPermission.DO.FindInBatches(result, batchSize, fc)
}

func (sysPermission sysPermissionDo) Attrs(attrs ...field.AssignExpr) *sysPermissionDo {
	return sysPermission.withDO(sysPermission.DO.Attrs(attrs...))
}

func (sysPermission sysPermissionDo) Assign(attrs ...field.AssignExpr) *sysPermissionDo {
	return sysPermission.withDO(sysPermission.DO.Assign(attrs...))
}

func (sysPermission sysPermissionDo) Joins(fields ...field.RelationField) *sysPermissionDo {
	for _, _f := range fields {
		sysPermission = *sysPermission.withDO(sysPermission.DO.Joins(_f))
	}
	return &sysPermission
}

func (sysPermission sysPermissionDo) Preload(fields ...field.RelationField) *sysPermissionDo {
	for _, _f := range fields {
		sysPermission = *sysPermission.withDO(sysPermission.DO.Preload(_f))
	}
	return &sysPermission
}

func (sysPermission sysPermissionDo) FirstOrInit() (*model.SysPermission, error) {
	if result, err := sysPermission.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysPermission), nil
	}
}

func (sysPermission sysPermissionDo) FirstOrCreate() (*model.SysPermission, error) {
	if result, err := sysPermission.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysPermission), nil
	}
}

func (sysPermission sysPermissionDo) FindByPage(offset int, limit int) (result []*model.SysPermission, count int64, err error) {
	result, err = sysPermission.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = sysPermission.Offset(-1).Limit(-1).Count()
	return
}

func (sysPermission sysPermissionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = sysPermission.Count()
	if err != nil {
		return
	}

	err = sysPermission.Offset(offset).Limit(limit).Scan(result)
	return
}

func (sysPermission sysPermissionDo) Scan(result interface{}) (err error) {
	return sysPermission.DO.Scan(result)
}

func (sysPermission sysPermissionDo) Delete(models ...*model.SysPermission) (result gen.ResultInfo, err error) {
	return sysPermission.DO.Delete(models)
}

func (sysPermission *sysPermissionDo) withDO(do gen.Dao) *sysPermissionDo {
	sysPermission.DO = *do.(*gen.DO)
	return sysPermission
}
