// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mh-sso-svc/internal/model"
)

func newSysRolePermission(db *gorm.DB, opts ...gen.DOOption) sysRolePermission {
	_sysRolePermission := sysRolePermission{}

	_sysRolePermission.sysRolePermissionDo.UseDB(db, opts...)
	_sysRolePermission.sysRolePermissionDo.UseModel(&model.SysRolePermission{})

	tableName := _sysRolePermission.sysRolePermissionDo.TableName()
	_sysRolePermission.ALL = field.NewAsterisk(tableName)
	_sysRolePermission.ID = field.NewUint64(tableName, "id")
	_sysRolePermission.RoleID = field.NewUint64(tableName, "role_id")
	_sysRolePermission.PermissionID = field.NewUint64(tableName, "permission_id")
	_sysRolePermission.CreateTime = field.NewTime(tableName, "create_time")

	_sysRolePermission.fillFieldMap()

	return _sysRolePermission
}

type sysRolePermission struct {
	sysRolePermissionDo

	ALL field.Asterisk
	ID field.Uint64
	RoleID field.Uint64 // 角色ID
	PermissionID field.Uint64 // 权限ID
	CreateTime field.Time

	fieldMap map[string]field.Expr
}

func (sysRolePermission sysRolePermission) Table(newTableName string) *sysRolePermission {
	sysRolePermission.sysRolePermissionDo.UseTable(newTableName)
	return sysRolePermission.updateTableName(newTableName)
}

func (sysRolePermission sysRolePermission) As(alias string) *sysRolePermission {
	sysRolePermission.sysRolePermissionDo.DO = *(sysRolePermission.sysRolePermissionDo.As(alias).(*gen.DO))
	return sysRolePermission.updateTableName(alias)
}

func (sysRolePermission *sysRolePermission) updateTableName(table string) *sysRolePermission {
	sysRolePermission.ALL = field.NewAsterisk(table)
	sysRolePermission.ID = field.NewUint64(table, "id")
	sysRolePermission.RoleID = field.NewUint64(table, "role_id")
	sysRolePermission.PermissionID = field.NewUint64(table, "permission_id")
	sysRolePermission.CreateTime = field.NewTime(table, "create_time")

	sysRolePermission.fillFieldMap()

	return sysRolePermission
}

func (sysRolePermission *sysRolePermission) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := sysRolePermission.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (sysRolePermission *sysRolePermission) fillFieldMap() {
	sysRolePermission.fieldMap = make(map[string]field.Expr, 4)
	sysRolePermission.fieldMap["id"] = sysRolePermission.ID
	sysRolePermission.fieldMap["role_id"] = sysRolePermission.RoleID
	sysRolePermission.fieldMap["permission_id"] = sysRolePermission.PermissionID
	sysRolePermission.fieldMap["create_time"] = sysRolePermission.CreateTime
}

func (sysRolePermission sysRolePermission) clone(db *gorm.DB) sysRolePermission {
	sysRolePermission.sysRolePermissionDo.ReplaceConnPool(db.Statement.ConnPool)
	return sysRolePermission
}

func (sysRolePermission sysRolePermission) replaceDB(db *gorm.DB) sysRolePermission {
	sysRolePermission.sysRolePermissionDo.ReplaceDB(db)
	return sysRolePermission
}

type sysRolePermissionDo struct{ gen.DO }

func (sysRolePermission sysRolePermissionDo) Debug() *sysRolePermissionDo {
	return sysRolePermission.withDO(sysRolePermission.DO.Debug())
}

func (sysRolePermission sysRolePermissionDo) WithContext(ctx context.Context) *sysRolePermissionDo {
	return sysRolePermission.withDO(sysRolePermission.DO.WithContext(ctx))
}

func (sysRolePermission sysRolePermissionDo) ReadDB() *sysRolePermissionDo {
	return sysRolePermission.Clauses(dbresolver.Read)
}

func (sysRolePermission sysRolePermissionDo) WriteDB() *sysRolePermissionDo {
	return sysRolePermission.Clauses(dbresolver.Write)
}

func (sysRolePermission sysRolePermissionDo) Session(config *gorm.Session) *sysRolePermissionDo {
	return sysRolePermission.withDO(sysRolePermission.DO.Session(config))
}

func (sysRolePermission sysRolePermissionDo) Clauses(conds ...clause.Expression) *sysRolePermissionDo {
	return sysRolePermission.withDO(sysRolePermission.DO.Clauses(conds...))
}

func (sysRolePermission sysRolePermissionDo) Returning(value interface{}, columns ...string) *sysRolePermissionDo {
	return sysRolePermission.withDO(sysRolePermission.DO.Returning(value, columns...))
}

func (sysRolePermission sysRolePermissionDo) Not(conds ...gen.Condition) *sysRolePermissionDo {
	return sysRolePermission.withDO(sysRolePermission.DO.Not(conds...))
}

func (sysRolePermission sysRolePermissionDo) Or(conds ...gen.Condition) *sysRolePermissionDo {
	return sysRolePermission.withDO(sysRolePermission.DO.Or(conds...))
}

func (sysRolePermission sysRolePermissionDo) Select(conds ...field.Expr) *sysRolePermissionDo {
	return sysRolePermission.withDO(sysRolePermission.DO.Select(conds...))
}

func (sysRolePermission sysRolePermissionDo) Where(conds ...gen.Condition) *sysRolePermissionDo {
	return sysRolePermission.withDO(sysRolePermission.DO.Where(conds...))
}

func (sysRolePermission sysRolePermissionDo) Order(conds ...field.Expr) *sysRolePermissionDo {
	return sysRolePermission.withDO(sysRolePermission.DO.Order(conds...))
}

func (sysRolePermission sysRolePermissionDo) Distinct(cols ...field.Expr) *sysRolePermissionDo {
	return sysRolePermission.withDO(sysRolePermission.DO.Distinct(cols...))
}

func (sysRolePermission sysRolePermissionDo) Omit(cols ...field.Expr) *sysRolePermissionDo {
	return sysRolePermission.withDO(sysRolePermission.DO.Omit(cols...))
}

func (sysRolePermission sysRolePermissionDo) Join(table schema.Tabler, on ...field.Expr) *sysRolePermissionDo {
	return sysRolePermission.withDO(sysRolePermission.DO.Join(table, on...))
}

func (sysRolePermission sysRolePermissionDo) LeftJoin(table schema.Tabler, on ...field.Expr) *sysRolePermissionDo {
	return sysRolePermission.withDO(sysRolePermission.DO.LeftJoin(table, on...))
}

func (sysRolePermission sysRolePermissionDo) RightJoin(table schema.Tabler, on ...field.Expr) *sysRolePermissionDo {
	return sysRolePermission.withDO(sysRolePermission.DO.RightJoin(table, on...))
}

func (sysRolePermission sysRolePermissionDo) Group(cols ...field.Expr) *sysRolePermissionDo {
	return sysRolePermission.withDO(sysRolePermission.DO.Group(cols...))
}

func (sysRolePermission sysRolePermissionDo) Having(conds ...gen.Condition) *sysRolePermissionDo {
	return sysRolePermission.withDO(sysRolePermission.DO.Having(conds...))
}

func (sysRolePermission sysRolePermissionDo) Limit(limit int) *sysRolePermissionDo {
	return sysRolePermission.withDO(sysRolePermission.DO.Limit(limit))
}

func (sysRolePermission sysRolePermissionDo) Offset(offset int) *sysRolePermissionDo {
	return sysRolePermission.withDO(sysRolePermission.DO.Offset(offset))
}

func (sysRolePermission sysRolePermissionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *sysRolePermissionDo {
	return sysRolePermission.withDO(sysRolePermission.DO.Scopes(funcs...))
}

func (sysRolePermission sysRolePermissionDo) Unscoped() *sysRolePermissionDo {
	return sysRolePermission.withDO(sysRolePermission.DO.Unscoped())
}

func (sysRolePermission sysRolePermissionDo) Create(values ...*model.SysRolePermission) error {
	if len(values) == 0 {
		return nil
	}
	return sysRolePermission.DO.Create(values)
}

func (sysRolePermission sysRolePermissionDo) CreateInBatches(values []*model.SysRolePermission, batchSize int) error {
	return sysRolePermission.DO.CreateInBatches(values, batchSize)
}

func (sysRolePermission sysRolePermissionDo) Save(values ...*model.SysRolePermission) error {
	if len(values) == 0 {
		return nil
	}
	return sysRolePermission.DO.Save(values)
}

func (sysRolePermission sysRolePermissionDo) First() (*model.SysRolePermission, error) {
	if result, err := sysRolePermission.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRolePermission), nil
	}
}

func (sysRolePermission sysRolePermissionDo) Take() (*model.SysRolePermission, error) {
	if result, err := sysRolePermission.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRolePermission), nil
	}
}

func (sysRolePermission sysRolePermissionDo) Last() (*model.SysRolePermission, error) {
	if result, err := sysRolePermission.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRolePermission), nil
	}
}

func (sysRolePermission sysRolePermissionDo) Find() ([]*model.SysRolePermission, error) {
	result, err := sysRolePermission.DO.Find()
	return result.([]*model.SysRolePermission), err
}

func (sysRolePermission sysRolePermissionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysRolePermission, err error) {
	buf := make([]*model.SysRolePermission, 0, batchSize)
	err = sysRolePermission.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (sysRolePermission sysRolePermissionDo) FindInBatches(result *[]*model.SysRolePermission, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return sysRolePermission.DO.FindInBatches(result, batchSize, fc)
}

func (sysRolePermission sysRolePermissionDo) Attrs(attrs ...field.AssignExpr) *sysRolePermissionDo {
	return sysRolePermission.withDO(sysRolePermission.DO.Attrs(attrs...))
}

func (sysRolePermission sysRolePermissionDo) Assign(attrs ...field.AssignExpr) *sysRolePermissionDo {
	return sysRolePermission.withDO(sysRolePermission.DO.Assign(attrs...))
}

func (sysRolePermission sysRolePermissionDo) Joins(fields ...field.RelationField) *sysRolePermissionDo {
	for _, _f := range fields {
		sysRolePermission = *sysRolePermission.withDO(sysRolePermission.DO.Joins(_f))
	}
	return &sysRolePermission
}

func (sysRolePermission sysRolePermissionDo) Preload(fields ...field.RelationField) *sysRolePermissionDo {
	for _, _f := range fields {
		sysRolePermission = *sysRolePermission.withDO(sysRolePermission.DO.Preload(_f))
	}
	return &sysRolePermission
}

func (sysRolePermission sysRolePermissionDo) FirstOrInit() (*model.SysRolePermission, error) {
	if result, err := sysRolePermission.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRolePermission), nil
	}
}

func (sysRolePermission sysRolePermissionDo) FirstOrCreate() (*model.SysRolePermission, error) {
	if result, err := sysRolePermission.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRolePermission), nil
	}
}

func (sysRolePermission sysRolePermissionDo) FindByPage(offset int, limit int) (result []*model.SysRolePermission, count int64, err error) {
	result, err = sysRolePermission.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = sysRolePermission.Offset(-1).Limit(-1).Count()
	return
}

func (sysRolePermission sysRolePermissionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = sysRolePermission.Count()
	if err != nil {
		return
	}

	err = sysRolePermission.Offset(offset).Limit(limit).Scan(result)
	return
}

func (sysRolePermission sysRolePermissionDo) Scan(result interface{}) (err error) {
	return sysRolePermission.DO.Scan(result)
}

func (sysRolePermission sysRolePermissionDo) Delete(models ...*model.SysRolePermission) (result gen.ResultInfo, err error) {
	return sysRolePermission.DO.Delete(models)
}

func (sysRolePermission *sysRolePermissionDo) withDO(do gen.Dao) *sysRolePermissionDo {
	sysRolePermission.DO = *do.(*gen.DO)
	return sysRolePermission
}
