// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mh-sso-svc/internal/model"
)

func newSysRole(db *gorm.DB, opts ...gen.DOOption) sysRole {
	_sysRole := sysRole{}

	_sysRole.sysRoleDo.UseDB(db, opts...)
	_sysRole.sysRoleDo.UseModel(&model.SysRole{})

	tableName := _sysRole.sysRoleDo.TableName()
	_sysRole.ALL = field.NewAsterisk(tableName)
	_sysRole.ID = field.NewUint64(tableName, "id")
	_sysRole.Code = field.NewString(tableName, "code")
	_sysRole.Name = field.NewString(tableName, "name")
	_sysRole.Description = field.NewString(tableName, "description")
	_sysRole.IsBuiltin = field.NewInt32(tableName, "is_builtin")
	_sysRole.Status = field.NewInt32(tableName, "status")
	_sysRole.CreateTime = field.NewTime(tableName, "create_time")
	_sysRole.UpdateTime = field.NewTime(tableName, "update_time")

	_sysRole.fillFieldMap()

	return _sysRole
}

type sysRole struct {
	sysRoleDo

	ALL field.Asterisk
	ID field.Uint64
	Code field.String // 角色编码
	Name field.String // 角色名称
	Description field.String // 角色描述
	IsBuiltin field.Int32 // 内置角色
	Status field.Int32 // 状态
	CreateTime field.Time
	UpdateTime field.Time

	fieldMap map[string]field.Expr
}

func (sysRole sysRole) Table(newTableName string) *sysRole {
	sysRole.sysRoleDo.UseTable(newTableName)
	return sysRole.updateTableName(newTableName)
}

func (sysRole sysRole) As(alias string) *sysRole {
	sysRole.sysRoleDo.DO = *(sysRole.sysRoleDo.As(alias).(*gen.DO))
	return sysRole.updateTableName(alias)
}

func (sysRole *sysRole) updateTableName(table string) *sysRole {
	sysRole.ALL = field.NewAsterisk(table)
	sysRole.ID = field.NewUint64(table, "id")
	sysRole.Code = field.NewString(table, "code")
	sysRole.Name = field.NewString(table, "name")
	sysRole.Description = field.NewString(table, "description")
	sysRole.IsBuiltin = field.NewInt32(table, "is_builtin")
	sysRole.Status = field.NewInt32(table, "status")
	sysRole.CreateTime = field.NewTime(table, "create_time")
	sysRole.UpdateTime = field.NewTime(table, "update_time")

	sysRole.fillFieldMap()

	return sysRole
}

func (sysRole *sysRole) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := sysRole.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (sysRole *sysRole) fillFieldMap() {
	sysRole.fieldMap = make(map[string]field.Expr, 8)
	sysRole.fieldMap["id"] = sysRole.ID
	sysRole.fieldMap["code"] = sysRole.Code
	sysRole.fieldMap["name"] = sysRole.Name
	sysRole.fieldMap["description"] = sysRole.Description
	sysRole.fieldMap["is_builtin"] = sysRole.IsBuiltin
	sysRole.fieldMap["status"] = sysRole.Status
	sysRole.fieldMap["create_time"] = sysRole.CreateTime
	sysRole.fieldMap["update_time"] = sysRole.UpdateTime
}

func (sysRole sysRole) clone(db *gorm.DB) sysRole {
	sysRole.sysRoleDo.ReplaceConnPool(db.Statement.ConnPool)
	return sysRole
}

func (sysRole sysRole) replaceDB(db *gorm.DB) sysRole {
	sysRole.sysRoleDo.ReplaceDB(db)
	return sysRole
}

type sysRoleDo struct{ gen.DO }

func (sysRole sysRoleDo) Debug() *sysRoleDo {
	return sysRole.withDO(sysRole.DO.Debug())
}

func (sysRole sysRoleDo) WithContext(ctx context.Context) *sysRoleDo {
	return sysRole.withDO(sysRole.DO.WithContext(ctx))
}

func (sysRole sysRoleDo) ReadDB() *sysRoleDo {
	return sysRole.Clauses(dbresolver.Read)
}

func (sysRole sysRoleDo) WriteDB() *sysRoleDo {
	return sysRole.Clauses(dbresolver.Write)
}

func (sysRole sysRoleDo) Session(config *gorm.Session) *sysRoleDo {
	return sysRole.withDO(sysRole.DO.Session(config))
}

func (sysRole sysRoleDo) Clauses(conds ...clause.Expression) *sysRoleDo {
	return sysRole.withDO(sysRole.DO.Clauses(conds...))
}

func (sysRole sysRoleDo) Returning(value interface{}, columns ...string) *sysRoleDo {
	return sysRole.withDO(sysRole.DO.Returning(value, columns...))
}

func (sysRole sysRoleDo) Not(conds ...gen.Condition) *sysRoleDo {
	return sysRole.withDO(sysRole.DO.Not(conds...))
}

func (sysRole sysRoleDo) Or(conds ...gen.Condition) *sysRoleDo {
	return sysRole.withDO(sysRole.DO.Or(conds...))
}

func (sysRole sysRoleDo) Select(conds ...field.Expr) *sysRoleDo {
	return sysRole.withDO(sysRole.DO.Select(conds...))
}

func (sysRole sysRoleDo) Where(conds ...gen.Condition) *sysRoleDo {
	return sysRole.withDO(sysRole.DO.Where(conds...))
}

func (sysRole sysRoleDo) Order(conds ...field.Expr) *sysRoleDo {
	return sysRole.withDO(sysRole.DO.Order(conds...))
}

func (sysRole sysRoleDo) Distinct(cols ...field.Expr) *sysRoleDo {
	return sysRole.withDO(sysRole.DO.Distinct(cols...))
}

func (sysRole sysRoleDo) Omit(cols ...field.Expr) *sysRoleDo {
	return sysRole.withDO(sysRole.DO.Omit(cols...))
}

func (sysRole sysRoleDo) Join(table schema.Tabler, on ...field.Expr) *sysRoleDo {
	return sysRole.withDO(sysRole.DO.Join(table, on...))
}

func (sysRole sysRoleDo) LeftJoin(table schema.Tabler, on ...field.Expr) *sysRoleDo {
	return sysRole.withDO(sysRole.DO.LeftJoin(table, on...))
}

func (sysRole sysRoleDo) RightJoin(table schema.Tabler, on ...field.Expr) *sysRoleDo {
	return sysRole.withDO(sysRole.DO.RightJoin(table, on...))
}

func (sysRole sysRoleDo) Group(cols ...field.Expr) *sysRoleDo {
	return sysRole.withDO(sysRole.DO.Group(cols...))
}

func (sysRole sysRoleDo) Having(conds ...gen.Condition) *sysRoleDo {
	return sysRole.withDO(sysRole.DO.Having(conds...))
}

func (sysRole sysRoleDo) Limit(limit int) *sysRoleDo {
	return sysRole.withDO(sysRole.DO.Limit(limit))
}

func (sysRole sysRoleDo) Offset(offset int) *sysRoleDo {
	return sysRole.withDO(sysRole.DO.Offset(offset))
}

func (sysRole sysRoleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *sysRoleDo {
	return sysRole.withDO(sysRole.DO.Scopes(funcs...))
}

func (sysRole sysRoleDo) Unscoped() *sysRoleDo {
	return sysRole.withDO(sysRole.DO.Unscoped())
}

func (sysRole sysRoleDo) Create(values ...*model.SysRole) error {
	if len(values) == 0 {
		return nil
	}
	return sysRole.DO.Create(values)
}

func (sysRole sysRoleDo) CreateInBatches(values []*model.SysRole, batchSize int) error {
	return sysRole.DO.CreateInBatches(values, batchSize)
}

func (sysRole sysRoleDo) Save(values ...*model.SysRole) error {
	if len(values) == 0 {
		return nil
	}
	return sysRole.DO.Save(values)
}

func (sysRole sysRoleDo) First() (*model.SysRole, error) {
	if result, err := sysRole.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRole), nil
	}
}

func (sysRole sysRoleDo) Take() (*model.SysRole, error) {
	if result, err := sysRole.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRole), nil
	}
}

func (sysRole sysRoleDo) Last() (*model.SysRole, error) {
	if result, err := sysRole.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRole), nil
	}
}

func (sysRole sysRoleDo) Find() ([]*model.SysRole, error) {
	result, err := sysRole.DO.Find()
	return result.([]*model.SysRole), err
}

func (sysRole sysRoleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysRole, err error) {
	buf := make([]*model.SysRole, 0, batchSize)
	err = sysRole.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (sysRole sysRoleDo) FindInBatches(result *[]*model.SysRole, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return sysRole.DO.FindInBatches(result, batchSize, fc)
}

func (sysRole sysRoleDo) Attrs(attrs ...field.AssignExpr) *sysRoleDo {
	return sysRole.withDO(sysRole.DO.Attrs(attrs...))
}

func (sysRole sysRoleDo) Assign(attrs ...field.AssignExpr) *sysRoleDo {
	return sysRole.withDO(sysRole.DO.Assign(attrs...))
}

func (sysRole sysRoleDo) Joins(fields ...field.RelationField) *sysRoleDo {
	for _, _f := range fields {
		sysRole = *sysRole.withDO(sysRole.DO.Joins(_f))
	}
	return &sysRole
}

func (sysRole sysRoleDo) Preload(fields ...field.RelationField) *sysRoleDo {
	for _, _f := range fields {
		sysRole = *sysRole.withDO(sysRole.DO.Preload(_f))
	}
	return &sysRole
}

func (sysRole sysRoleDo) FirstOrInit() (*model.SysRole, error) {
	if result, err := sysRole.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRole), nil
	}
}

func (sysRole sysRoleDo) FirstOrCreate() (*model.SysRole, error) {
	if result, err := sysRole.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRole), nil
	}
}

func (sysRole sysRoleDo) FindByPage(offset int, limit int) (result []*model.SysRole, count int64, err error) {
	result, err = sysRole.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = sysRole.Offset(-1).Limit(-1).Count()
	return
}

func (sysRole sysRoleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = sysRole.Count()
	if err != nil {
		return
	}

	err = sysRole.Offset(offset).Limit(limit).Scan(result)
	return
}

func (sysRole sysRoleDo) Scan(result interface{}) (err error) {
	return sysRole.DO.Scan(result)
}

func (sysRole sysRoleDo) Delete(models ...*model.SysRole) (result gen.ResultInfo, err error) {
	return sysRole.DO.Delete(models)
}

func (sysRole *sysRoleDo) withDO(do gen.Dao) *sysRoleDo {
	sysRole.DO = *do.(*gen.DO)
	return sysRole
}
