// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mh-sso-svc/internal/model"
)

func newSysUser(db *gorm.DB, opts ...gen.DOOption) sysUser {
	_sysUser := sysUser{}

	_sysUser.sysUserDo.UseDB(db, opts...)
	_sysUser.sysUserDo.UseModel(&model.SysUser{})

	tableName := _sysUser.sysUserDo.TableName()
	_sysUser.ALL = field.NewAsterisk(tableName)
	_sysUser.ID = field.NewUint64(tableName, "id")
	_sysUser.Account = field.NewString(tableName, "account")
	_sysUser.Password = field.NewString(tableName, "password")
	_sysUser.Name = field.NewString(tableName, "name")
	_sysUser.Phone = field.NewString(tableName, "phone")
	_sysUser.Email = field.NewString(tableName, "email")
	_sysUser.Department = field.NewString(tableName, "department")
	_sysUser.PasswordVersion = field.NewInt32(tableName, "password_version")
	_sysUser.CreateTime = field.NewTime(tableName, "create_time")
	_sysUser.UpdateTime = field.NewTime(tableName, "update_time")

	_sysUser.fillFieldMap()

	return _sysUser
}

type sysUser struct {
	sysUserDo

	ALL field.Asterisk
	ID field.Uint64
	Account field.String // 登录账号
	Password field.String // 密码(bcrypt加密,SSO登录校验)
	Name field.String // 姓名
	Phone field.String // 手机号
	Email field.String // 邮箱
	Department field.String // 所属部门
	PasswordVersion field.Int32 // 密码版本
	CreateTime field.Time
	UpdateTime field.Time

	fieldMap map[string]field.Expr
}

func (sysUser sysUser) Table(newTableName string) *sysUser {
	sysUser.sysUserDo.UseTable(newTableName)
	return sysUser.updateTableName(newTableName)
}

func (sysUser sysUser) As(alias string) *sysUser {
	sysUser.sysUserDo.DO = *(sysUser.sysUserDo.As(alias).(*gen.DO))
	return sysUser.updateTableName(alias)
}

func (sysUser *sysUser) updateTableName(table string) *sysUser {
	sysUser.ALL = field.NewAsterisk(table)
	sysUser.ID = field.NewUint64(table, "id")
	sysUser.Account = field.NewString(table, "account")
	sysUser.Password = field.NewString(table, "password")
	sysUser.Name = field.NewString(table, "name")
	sysUser.Phone = field.NewString(table, "phone")
	sysUser.Email = field.NewString(table, "email")
	sysUser.Department = field.NewString(table, "department")
	sysUser.PasswordVersion = field.NewInt32(table, "password_version")
	sysUser.CreateTime = field.NewTime(table, "create_time")
	sysUser.UpdateTime = field.NewTime(table, "update_time")

	sysUser.fillFieldMap()

	return sysUser
}

func (sysUser *sysUser) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := sysUser.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (sysUser *sysUser) fillFieldMap() {
	sysUser.fieldMap = make(map[string]field.Expr, 10)
	sysUser.fieldMap["id"] = sysUser.ID
	sysUser.fieldMap["account"] = sysUser.Account
	sysUser.fieldMap["password"] = sysUser.Password
	sysUser.fieldMap["name"] = sysUser.Name
	sysUser.fieldMap["phone"] = sysUser.Phone
	sysUser.fieldMap["email"] = sysUser.Email
	sysUser.fieldMap["department"] = sysUser.Department
	sysUser.fieldMap["password_version"] = sysUser.PasswordVersion
	sysUser.fieldMap["create_time"] = sysUser.CreateTime
	sysUser.fieldMap["update_time"] = sysUser.UpdateTime
}

func (sysUser sysUser) clone(db *gorm.DB) sysUser {
	sysUser.sysUserDo.ReplaceConnPool(db.Statement.ConnPool)
	return sysUser
}

func (sysUser sysUser) replaceDB(db *gorm.DB) sysUser {
	sysUser.sysUserDo.ReplaceDB(db)
	return sysUser
}

type sysUserDo struct{ gen.DO }

func (sysUser sysUserDo) Debug() *sysUserDo {
	return sysUser.withDO(sysUser.DO.Debug())
}

func (sysUser sysUserDo) WithContext(ctx context.Context) *sysUserDo {
	return sysUser.withDO(sysUser.DO.WithContext(ctx))
}

func (sysUser sysUserDo) ReadDB() *sysUserDo {
	return sysUser.Clauses(dbresolver.Read)
}

func (sysUser sysUserDo) WriteDB() *sysUserDo {
	return sysUser.Clauses(dbresolver.Write)
}

func (sysUser sysUserDo) Session(config *gorm.Session) *sysUserDo {
	return sysUser.withDO(sysUser.DO.Session(config))
}

func (sysUser sysUserDo) Clauses(conds ...clause.Expression) *sysUserDo {
	return sysUser.withDO(sysUser.DO.Clauses(conds...))
}

func (sysUser sysUserDo) Returning(value interface{}, columns ...string) *sysUserDo {
	return sysUser.withDO(sysUser.DO.Returning(value, columns...))
}

func (sysUser sysUserDo) Not(conds ...gen.Condition) *sysUserDo {
	return sysUser.withDO(sysUser.DO.Not(conds...))
}

func (sysUser sysUserDo) Or(conds ...gen.Condition) *sysUserDo {
	return sysUser.withDO(sysUser.DO.Or(conds...))
}

func (sysUser sysUserDo) Select(conds ...field.Expr) *sysUserDo {
	return sysUser.withDO(sysUser.DO.Select(conds...))
}

func (sysUser sysUserDo) Where(conds ...gen.Condition) *sysUserDo {
	return sysUser.withDO(sysUser.DO.Where(conds...))
}

func (sysUser sysUserDo) Order(conds ...field.Expr) *sysUserDo {
	return sysUser.withDO(sysUser.DO.Order(conds...))
}

func (sysUser sysUserDo) Distinct(cols ...field.Expr) *sysUserDo {
	return sysUser.withDO(sysUser.DO.Distinct(cols...))
}

func (sysUser sysUserDo) Omit(cols ...field.Expr) *sysUserDo {
	return sysUser.withDO(sysUser.DO.Omit(cols...))
}

func (sysUser sysUserDo) Join(table schema.Tabler, on ...field.Expr) *sysUserDo {
	return sysUser.withDO(sysUser.DO.Join(table, on...))
}

func (sysUser sysUserDo) LeftJoin(table schema.Tabler, on ...field.Expr) *sysUserDo {
	return sysUser.withDO(sysUser.DO.LeftJoin(table, on...))
}

func (sysUser sysUserDo) RightJoin(table schema.Tabler, on ...field.Expr) *sysUserDo {
	return sysUser.withDO(sysUser.DO.RightJoin(table, on...))
}

func (sysUser sysUserDo) Group(cols ...field.Expr) *sysUserDo {
	return sysUser.withDO(sysUser.DO.Group(cols...))
}

func (sysUser sysUserDo) Having(conds ...gen.Condition) *sysUserDo {
	return sysUser.withDO(sysUser.DO.Having(conds...))
}

func (sysUser sysUserDo) Limit(limit int) *sysUserDo {
	return sysUser.withDO(sysUser.DO.Limit(limit))
}

func (sysUser sysUserDo) Offset(offset int) *sysUserDo {
	return sysUser.withDO(sysUser.DO.Offset(offset))
}

func (sysUser sysUserDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *sysUserDo {
	return sysUser.withDO(sysUser.DO.Scopes(funcs...))
}

func (sysUser sysUserDo) Unscoped() *sysUserDo {
	return sysUser.withDO(sysUser.DO.Unscoped())
}

func (sysUser sysUserDo) Create(values ...*model.SysUser) error {
	if len(values) == 0 {
		return nil
	}
	return sysUser.DO.Create(values)
}

func (sysUser sysUserDo) CreateInBatches(values []*model.SysUser, batchSize int) error {
	return sysUser.DO.CreateInBatches(values, batchSize)
}

func (sysUser sysUserDo) Save(values ...*model.SysUser) error {
	if len(values) == 0 {
		return nil
	}
	return sysUser.DO.Save(values)
}

func (sysUser sysUserDo) First() (*model.SysUser, error) {
	if result, err := sysUser.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUser), nil
	}
}

func (sysUser sysUserDo) Take() (*model.SysUser, error) {
	if result, err := sysUser.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUser), nil
	}
}

func (sysUser sysUserDo) Last() (*model.SysUser, error) {
	if result, err := sysUser.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUser), nil
	}
}

func (sysUser sysUserDo) Find() ([]*model.SysUser, error) {
	result, err := sysUser.DO.Find()
	return result.([]*model.SysUser), err
}

func (sysUser sysUserDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysUser, err error) {
	buf := make([]*model.SysUser, 0, batchSize)
	err = sysUser.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (sysUser sysUserDo) FindInBatches(result *[]*model.SysUser, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return sysUser.DO.FindInBatches(result, batchSize, fc)
}

func (sysUser sysUserDo) Attrs(attrs ...field.AssignExpr) *sysUserDo {
	return sysUser.withDO(sysUser.DO.Attrs(attrs...))
}

func (sysUser sysUserDo) Assign(attrs ...field.AssignExpr) *sysUserDo {
	return sysUser.withDO(sysUser.DO.Assign(attrs...))
}

func (sysUser sysUserDo) Joins(fields ...field.RelationField) *sysUserDo {
	for _, _f := range fields {
		sysUser = *sysUser.withDO(sysUser.DO.Joins(_f))
	}
	return &sysUser
}

func (sysUser sysUserDo) Preload(fields ...field.RelationField) *sysUserDo {
	for _, _f := range fields {
		sysUser = *sysUser.withDO(sysUser.DO.Preload(_f))
	}
	return &sysUser
}

func (sysUser sysUserDo) FirstOrInit() (*model.SysUser, error) {
	if result, err := sysUser.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUser), nil
	}
}

func (sysUser sysUserDo) FirstOrCreate() (*model.SysUser, error) {
	if result, err := sysUser.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUser), nil
	}
}

func (sysUser sysUserDo) FindByPage(offset int, limit int) (result []*model.SysUser, count int64, err error) {
	result, err = sysUser.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = sysUser.Offset(-1).Limit(-1).Count()
	return
}

func (sysUser sysUserDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = sysUser.Count()
	if err != nil {
		return
	}

	err = sysUser.Offset(offset).Limit(limit).Scan(result)
	return
}

func (sysUser sysUserDo) Scan(result interface{}) (err error) {
	return sysUser.DO.Scan(result)
}

func (sysUser sysUserDo) Delete(models ...*model.SysUser) (result gen.ResultInfo, err error) {
	return sysUser.DO.Delete(models)
}

func (sysUser *sysUserDo) withDO(do gen.Dao) *sysUserDo {
	sysUser.DO = *do.(*gen.DO)
	return sysUser
}
