// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameSysRolePermission = "sys_role_permission"

// SysRolePermission 角色-权限关系表
type SysRolePermission struct {
	ID           uint64    `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RoleID       uint64    `gorm:"column:role_id;not null;comment:角色ID" json:"role_id"`             // 角色ID
	PermissionID uint64    `gorm:"column:permission_id;not null;comment:权限ID" json:"permission_id"` // 权限ID
	CreateTime   time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
}

// TableName SysRolePermission's table name
func (*SysRolePermission) TableName() string {
	return TableNameSysRolePermission
}
