// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameSysPermission = "sys_permission"

// SysPermission 权限表
type SysPermission struct {
	ID         uint64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	PlatformID uint64  `gorm:"column:platform_id;not null;comment:所属平台ID" json:"platform_id"`              // 所属平台ID
	Code       string  `gorm:"column:code;not null;comment:权限编码" json:"code"`                                // 权限编码
	Name       string  `gorm:"column:name;not null;comment:权限名称" json:"name"`                                // 权限名称
	Type       int32   `gorm:"column:type;not null;default:2;comment:类型: 1菜单 2API" json:"type"`              // 类型
	ParentID   *uint64 `gorm:"column:parent_id;comment:父权限ID" json:"parent_id"`                              // 父权限ID
	Sort       int32   `gorm:"column:sort;not null;default:0;comment:同级排序" json:"sort"`                      // 同级排序
	Status     int32   `gorm:"column:status;not null;default:1;comment:状态: 1启用 0禁用" json:"status"`          // 状态
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName SysPermission's table name
func (*SysPermission) TableName() string {
	return TableNameSysPermission
}
