// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameSysUserPlatform = "sys_user_platform"

// SysUserPlatform 用户平台权限关系表
type SysUserPlatform struct {
	ID         uint64    `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID     uint64    `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`         // 用户ID
	PlatformID uint64    `gorm:"column:platform_id;not null;comment:平台ID" json:"platform_id"` // 平台ID
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
}

// TableName SysUserPlatform's table name
func (*SysUserPlatform) TableName() string {
	return TableNameSysUserPlatform
}
