// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameSysUserRole = "sys_user_role"

// SysUserRole 用户-角色关系表
type SysUserRole struct {
	ID         uint64    `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID     uint64    `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`     // 用户ID
	RoleID     uint64    `gorm:"column:role_id;not null;comment:角色ID" json:"role_id"`     // 角色ID
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
}

// TableName SysUserRole's table name
func (*SysUserRole) TableName() string {
	return TableNameSysUserRole
}
