// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"permission-system/internal/db_model"
)

func newSysPlatform(db *gorm.DB, opts ...gen.DOOption) sysPlatform {
	_sysPlatform := sysPlatform{}

	_sysPlatform.sysPlatformDo.UseDB(db, opts...)
	_sysPlatform.sysPlatformDo.UseModel(&db_model.SysPlatform{})

	tableName := _sysPlatform.sysPlatformDo.TableName()
	_sysPlatform.ALL = field.NewAsterisk(tableName)
	_sysPlatform.ID = field.NewInt64(tableName, "id")
	_sysPlatform.Name = field.NewString(tableName, "name")
	_sysPlatform.Code = field.NewString(tableName, "code")
	_sysPlatform.CreatedBy = field.NewInt64(tableName, "created_by")
	_sysPlatform.UpdatedBy = field.NewInt64(tableName, "updated_by")
	_sysPlatform.RequestID = field.NewString(tableName, "request_id")
	_sysPlatform.CreateTime = field.NewTime(tableName, "create_time")
	_sysPlatform.UpdateTime = field.NewTime(tableName, "update_time")

	_sysPlatform.fillFieldMap()

	return _sysPlatform
}

// sysPlatform 平台表
type sysPlatform struct {
	sysPlatformDo

	ALL        field.Asterisk
	ID         field.Int64
	Name       field.String // 平台名称
	Code       field.String // 平台编码
	CreatedBy  field.Int64  // 创建操作人ID
	UpdatedBy  field.Int64  // 最后更新操作人ID
	RequestID  field.String // 最后一次写操作请求ID
	CreateTime field.Time
	UpdateTime field.Time

	fieldMap map[string]field.Expr
}

func (s sysPlatform) Table(newTableName string) *sysPlatform {
	s.sysPlatformDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysPlatform) As(alias string) *sysPlatform {
	s.sysPlatformDo.DO = *(s.sysPlatformDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysPlatform) updateTableName(table string) *sysPlatform {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.Name = field.NewString(table, "name")
	s.Code = field.NewString(table, "code")
	s.CreatedBy = field.NewInt64(table, "created_by")
	s.UpdatedBy = field.NewInt64(table, "updated_by")
	s.RequestID = field.NewString(table, "request_id")
	s.CreateTime = field.NewTime(table, "create_time")
	s.UpdateTime = field.NewTime(table, "update_time")

	s.fillFieldMap()

	return s
}

func (s *sysPlatform) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysPlatform) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 8)
	s.fieldMap["id"] = s.ID
	s.fieldMap["name"] = s.Name
	s.fieldMap["code"] = s.Code
	s.fieldMap["created_by"] = s.CreatedBy
	s.fieldMap["updated_by"] = s.UpdatedBy
	s.fieldMap["request_id"] = s.RequestID
	s.fieldMap["create_time"] = s.CreateTime
	s.fieldMap["update_time"] = s.UpdateTime
}

func (s sysPlatform) clone(db *gorm.DB) sysPlatform {
	s.sysPlatformDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysPlatform) replaceDB(db *gorm.DB) sysPlatform {
	s.sysPlatformDo.ReplaceDB(db)
	return s
}

type sysPlatformDo struct{ gen.DO }

func (s sysPlatformDo) Debug() *sysPlatformDo {
	return s.withDO(s.DO.Debug())
}

func (s sysPlatformDo) WithContext(ctx context.Context) *sysPlatformDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysPlatformDo) ReadDB() *sysPlatformDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysPlatformDo) WriteDB() *sysPlatformDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysPlatformDo) Session(config *gorm.Session) *sysPlatformDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysPlatformDo) Clauses(conds ...clause.Expression) *sysPlatformDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysPlatformDo) Returning(value interface{}, columns ...string) *sysPlatformDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysPlatformDo) Not(conds ...gen.Condition) *sysPlatformDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysPlatformDo) Or(conds ...gen.Condition) *sysPlatformDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysPlatformDo) Select(conds ...field.Expr) *sysPlatformDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysPlatformDo) Where(conds ...gen.Condition) *sysPlatformDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysPlatformDo) Order(conds ...field.Expr) *sysPlatformDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysPlatformDo) Distinct(cols ...field.Expr) *sysPlatformDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysPlatformDo) Omit(cols ...field.Expr) *sysPlatformDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysPlatformDo) Join(table schema.Tabler, on ...field.Expr) *sysPlatformDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysPlatformDo) LeftJoin(table schema.Tabler, on ...field.Expr) *sysPlatformDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysPlatformDo) RightJoin(table schema.Tabler, on ...field.Expr) *sysPlatformDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysPlatformDo) Group(cols ...field.Expr) *sysPlatformDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysPlatformDo) Having(conds ...gen.Condition) *sysPlatformDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysPlatformDo) Limit(limit int) *sysPlatformDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysPlatformDo) Offset(offset int) *sysPlatformDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysPlatformDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *sysPlatformDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysPlatformDo) Unscoped() *sysPlatformDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysPlatformDo) Create(values ...*db_model.SysPlatform) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysPlatformDo) CreateInBatches(values []*db_model.SysPlatform, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysPlatformDo) Save(values ...*db_model.SysPlatform) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysPlatformDo) First() (*db_model.SysPlatform, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.SysPlatform), nil
	}
}

func (s sysPlatformDo) Take() (*db_model.SysPlatform, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.SysPlatform), nil
	}
}

func (s sysPlatformDo) Last() (*db_model.SysPlatform, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.SysPlatform), nil
	}
}

func (s sysPlatformDo) Find() ([]*db_model.SysPlatform, error) {
	result, err := s.DO.Find()
	return result.([]*db_model.SysPlatform), err
}

func (s sysPlatformDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*db_model.SysPlatform, err error) {
	buf := make([]*db_model.SysPlatform, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysPlatformDo) FindInBatches(result *[]*db_model.SysPlatform, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysPlatformDo) Attrs(attrs ...field.AssignExpr) *sysPlatformDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysPlatformDo) Assign(attrs ...field.AssignExpr) *sysPlatformDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysPlatformDo) Joins(fields ...field.RelationField) *sysPlatformDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysPlatformDo) Preload(fields ...field.RelationField) *sysPlatformDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysPlatformDo) FirstOrInit() (*db_model.SysPlatform, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.SysPlatform), nil
	}
}

func (s sysPlatformDo) FirstOrCreate() (*db_model.SysPlatform, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.SysPlatform), nil
	}
}

func (s sysPlatformDo) FindByPage(offset int, limit int) (result []*db_model.SysPlatform, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysPlatformDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysPlatformDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysPlatformDo) Delete(models ...*db_model.SysPlatform) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysPlatformDo) withDO(do gen.Dao) *sysPlatformDo {
	s.DO = *do.(*gen.DO)
	return s
}
