
#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    gzip on;
    # gzip_static on;              # ✅ 让 Nginx 自动查找 .gz 文件
    gzip_types application/javascript text/css application/json;

    server {
        listen       3000;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;
        root /usr/share/nginx/html;
        # 默认首页
        index index.html;

        location / {
            add_header Cache-Control "no-cache, no-store, must-revalidate";
            add_header Pragma "no-cache";
            add_header Expires 0;
            try_files $uri /index.html;
        }
        # # API请求劫持与反向代理
        # location ^~/api/ {
        #     rewrite ^/api/(.*)$ /manage/$1 break;
        #     proxy_pass http://ssp.maplehaze.cn/;
        #     proxy_http_version 1.1;
        #     proxy_set_header Host ssp.maplehaze.cn;  # 修正Host头
        #     proxy_set_header X-Real-IP $remote_addr;
        #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #     proxy_set_header X-Forwarded-Proto $scheme;
        #     proxy_set_header Connection "";
            
        #     # 处理预检请求
        #     if ($request_method = 'OPTIONS') {
        #         add_header Access-Control-Allow-Origin *;
        #         add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS, PUT, DELETE';
        #         add_header Access-Control-Allow-Headers 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization';
        #         add_header Content-Length 0;
        #         add_header Content-Type text/plain;
        #         return 204;
        #     }
        # }
        # 确保 .js 文件的 MIME 类型为 application/javascript
        location ~* \.js$ {
            # gzip on;
            # gzip_static on; 
            # add_header Content-Encoding gzip;
            add_header Content-Type application/javascript;
            # try_files $uri $uri/assets;  # 如果找不到文件，回退到 index.html
        }
        
        location ~* \.css$ {
            # gzip on;
            # gzip_static on; 
            # add_header Content-Encoding gzip;
            add_header Content-Type text/css;
            # try_files $uri $uri/assets;  # 如果找不到文件，回退到 index.html
        }

        # location / {
        #     root   html;
        #     index  index.html index.htm;
        # }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        # proxy the PHP scripts to Apache listening on 127.0.0.1:80
        #
        #location ~ \.php$ {
        #    proxy_pass   http://127.0.0.1;
        #}

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        #location ~ \.php$ {
        #    root           html;
        #    fastcgi_pass   127.0.0.1:9000;
        #    fastcgi_index  index.php;
        #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
        #    include        fastcgi_params;
        #}

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #    deny  all;
        #}
    }
}