// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameSysUserRole = "sys_user_role"

// SysUserRole 用户-角色关系表
type SysUserRole struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID     int64     `gorm:"column:user_id;not null;comment:用户ID(sys_user.id)" json:"user_id"`                      // 用户ID(sys_user.id)
	RoleID     int64     `gorm:"column:role_id;not null;comment:角色ID(sys_role.id)" json:"role_id"`                      // 角色ID(sys_role.id)
	CreatedBy  *int64    `gorm:"column:created_by;comment:创建操作人ID" json:"created_by"`                                   // 创建操作人ID
	UpdatedBy  *int64    `gorm:"column:updated_by;comment:最后更新操作人ID" json:"updated_by"`                                 // 最后更新操作人ID
	RequestID  *string   `gorm:"column:request_id;comment:最后一次写操作请求ID" json:"request_id"`                               // 最后一次写操作请求ID
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:授权时间" json:"create_time"` // 授权时间
}

// TableName SysUserRole's table name
func (*SysUserRole) TableName() string {
	return TableNameSysUserRole
}
