// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"permission-system/internal/db_model"
)

func newSysRolePermission(db *gorm.DB, opts ...gen.DOOption) sysRolePermission {
	_sysRolePermission := sysRolePermission{}

	_sysRolePermission.sysRolePermissionDo.UseDB(db, opts...)
	_sysRolePermission.sysRolePermissionDo.UseModel(&db_model.SysRolePermission{})

	tableName := _sysRolePermission.sysRolePermissionDo.TableName()
	_sysRolePermission.ALL = field.NewAsterisk(tableName)
	_sysRolePermission.ID = field.NewInt64(tableName, "id")
	_sysRolePermission.RoleID = field.NewInt64(tableName, "role_id")
	_sysRolePermission.PermissionID = field.NewInt64(tableName, "permission_id")
	_sysRolePermission.CreatedBy = field.NewInt64(tableName, "created_by")
	_sysRolePermission.UpdatedBy = field.NewInt64(tableName, "updated_by")
	_sysRolePermission.RequestID = field.NewString(tableName, "request_id")
	_sysRolePermission.CreateTime = field.NewTime(tableName, "create_time")

	_sysRolePermission.fillFieldMap()

	return _sysRolePermission
}

// sysRolePermission 角色-权限关系表
type sysRolePermission struct {
	sysRolePermissionDo

	ALL          field.Asterisk
	ID           field.Int64
	RoleID       field.Int64  // 角色ID(sys_role.id)
	PermissionID field.Int64  // 权限ID(sys_permission.id)
	CreatedBy    field.Int64  // 创建操作人ID
	UpdatedBy    field.Int64  // 最后更新操作人ID
	RequestID    field.String // 最后一次写操作请求ID
	CreateTime   field.Time   // 授权时间

	fieldMap map[string]field.Expr
}

func (s sysRolePermission) Table(newTableName string) *sysRolePermission {
	s.sysRolePermissionDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysRolePermission) As(alias string) *sysRolePermission {
	s.sysRolePermissionDo.DO = *(s.sysRolePermissionDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysRolePermission) updateTableName(table string) *sysRolePermission {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.RoleID = field.NewInt64(table, "role_id")
	s.PermissionID = field.NewInt64(table, "permission_id")
	s.CreatedBy = field.NewInt64(table, "created_by")
	s.UpdatedBy = field.NewInt64(table, "updated_by")
	s.RequestID = field.NewString(table, "request_id")
	s.CreateTime = field.NewTime(table, "create_time")

	s.fillFieldMap()

	return s
}

func (s *sysRolePermission) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysRolePermission) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 7)
	s.fieldMap["id"] = s.ID
	s.fieldMap["role_id"] = s.RoleID
	s.fieldMap["permission_id"] = s.PermissionID
	s.fieldMap["created_by"] = s.CreatedBy
	s.fieldMap["updated_by"] = s.UpdatedBy
	s.fieldMap["request_id"] = s.RequestID
	s.fieldMap["create_time"] = s.CreateTime
}

func (s sysRolePermission) clone(db *gorm.DB) sysRolePermission {
	s.sysRolePermissionDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysRolePermission) replaceDB(db *gorm.DB) sysRolePermission {
	s.sysRolePermissionDo.ReplaceDB(db)
	return s
}

type sysRolePermissionDo struct{ gen.DO }

func (s sysRolePermissionDo) Debug() *sysRolePermissionDo {
	return s.withDO(s.DO.Debug())
}

func (s sysRolePermissionDo) WithContext(ctx context.Context) *sysRolePermissionDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysRolePermissionDo) ReadDB() *sysRolePermissionDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysRolePermissionDo) WriteDB() *sysRolePermissionDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysRolePermissionDo) Session(config *gorm.Session) *sysRolePermissionDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysRolePermissionDo) Clauses(conds ...clause.Expression) *sysRolePermissionDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysRolePermissionDo) Returning(value interface{}, columns ...string) *sysRolePermissionDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysRolePermissionDo) Not(conds ...gen.Condition) *sysRolePermissionDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysRolePermissionDo) Or(conds ...gen.Condition) *sysRolePermissionDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysRolePermissionDo) Select(conds ...field.Expr) *sysRolePermissionDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysRolePermissionDo) Where(conds ...gen.Condition) *sysRolePermissionDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysRolePermissionDo) Order(conds ...field.Expr) *sysRolePermissionDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysRolePermissionDo) Distinct(cols ...field.Expr) *sysRolePermissionDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysRolePermissionDo) Omit(cols ...field.Expr) *sysRolePermissionDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysRolePermissionDo) Join(table schema.Tabler, on ...field.Expr) *sysRolePermissionDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysRolePermissionDo) LeftJoin(table schema.Tabler, on ...field.Expr) *sysRolePermissionDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysRolePermissionDo) RightJoin(table schema.Tabler, on ...field.Expr) *sysRolePermissionDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysRolePermissionDo) Group(cols ...field.Expr) *sysRolePermissionDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysRolePermissionDo) Having(conds ...gen.Condition) *sysRolePermissionDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysRolePermissionDo) Limit(limit int) *sysRolePermissionDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysRolePermissionDo) Offset(offset int) *sysRolePermissionDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysRolePermissionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *sysRolePermissionDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysRolePermissionDo) Unscoped() *sysRolePermissionDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysRolePermissionDo) Create(values ...*db_model.SysRolePermission) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysRolePermissionDo) CreateInBatches(values []*db_model.SysRolePermission, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysRolePermissionDo) Save(values ...*db_model.SysRolePermission) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysRolePermissionDo) First() (*db_model.SysRolePermission, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.SysRolePermission), nil
	}
}

func (s sysRolePermissionDo) Take() (*db_model.SysRolePermission, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.SysRolePermission), nil
	}
}

func (s sysRolePermissionDo) Last() (*db_model.SysRolePermission, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.SysRolePermission), nil
	}
}

func (s sysRolePermissionDo) Find() ([]*db_model.SysRolePermission, error) {
	result, err := s.DO.Find()
	return result.([]*db_model.SysRolePermission), err
}

func (s sysRolePermissionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*db_model.SysRolePermission, err error) {
	buf := make([]*db_model.SysRolePermission, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysRolePermissionDo) FindInBatches(result *[]*db_model.SysRolePermission, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysRolePermissionDo) Attrs(attrs ...field.AssignExpr) *sysRolePermissionDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysRolePermissionDo) Assign(attrs ...field.AssignExpr) *sysRolePermissionDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysRolePermissionDo) Joins(fields ...field.RelationField) *sysRolePermissionDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysRolePermissionDo) Preload(fields ...field.RelationField) *sysRolePermissionDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysRolePermissionDo) FirstOrInit() (*db_model.SysRolePermission, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.SysRolePermission), nil
	}
}

func (s sysRolePermissionDo) FirstOrCreate() (*db_model.SysRolePermission, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.SysRolePermission), nil
	}
}

func (s sysRolePermissionDo) FindByPage(offset int, limit int) (result []*db_model.SysRolePermission, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysRolePermissionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysRolePermissionDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysRolePermissionDo) Delete(models ...*db_model.SysRolePermission) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysRolePermissionDo) withDO(do gen.Dao) *sysRolePermissionDo {
	s.DO = *do.(*gen.DO)
	return s
}
