// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mh-sso-svc/internal/db_model"
)

func newSysUserPlatform(db *gorm.DB, opts ...gen.DOOption) sysUserPlatform {
	_sysUserPlatform := sysUserPlatform{}

	_sysUserPlatform.sysUserPlatformDo.UseDB(db, opts...)
	_sysUserPlatform.sysUserPlatformDo.UseModel(&db_model.SysUserPlatform{})

	tableName := _sysUserPlatform.sysUserPlatformDo.TableName()
	_sysUserPlatform.ALL = field.NewAsterisk(tableName)
	_sysUserPlatform.ID = field.NewUint64(tableName, "id")
	_sysUserPlatform.UserID = field.NewUint64(tableName, "user_id")
	_sysUserPlatform.PlatformID = field.NewUint64(tableName, "platform_id")
	_sysUserPlatform.CreateTime = field.NewTime(tableName, "create_time")

	_sysUserPlatform.fillFieldMap()

	return _sysUserPlatform
}

type sysUserPlatform struct {
	sysUserPlatformDo

	ALL field.Asterisk
	ID field.Uint64
	UserID field.Uint64 // 用户ID
	PlatformID field.Uint64 // 平台ID
	CreateTime field.Time

	fieldMap map[string]field.Expr
}

func (sysUserPlatform sysUserPlatform) Table(newTableName string) *sysUserPlatform {
	sysUserPlatform.sysUserPlatformDo.UseTable(newTableName)
	return sysUserPlatform.updateTableName(newTableName)
}

func (sysUserPlatform sysUserPlatform) As(alias string) *sysUserPlatform {
	sysUserPlatform.sysUserPlatformDo.DO = *(sysUserPlatform.sysUserPlatformDo.As(alias).(*gen.DO))
	return sysUserPlatform.updateTableName(alias)
}

func (sysUserPlatform *sysUserPlatform) updateTableName(table string) *sysUserPlatform {
	sysUserPlatform.ALL = field.NewAsterisk(table)
	sysUserPlatform.ID = field.NewUint64(table, "id")
	sysUserPlatform.UserID = field.NewUint64(table, "user_id")
	sysUserPlatform.PlatformID = field.NewUint64(table, "platform_id")
	sysUserPlatform.CreateTime = field.NewTime(table, "create_time")

	sysUserPlatform.fillFieldMap()

	return sysUserPlatform
}

func (sysUserPlatform *sysUserPlatform) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := sysUserPlatform.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (sysUserPlatform *sysUserPlatform) fillFieldMap() {
	sysUserPlatform.fieldMap = make(map[string]field.Expr, 4)
	sysUserPlatform.fieldMap["id"] = sysUserPlatform.ID
	sysUserPlatform.fieldMap["user_id"] = sysUserPlatform.UserID
	sysUserPlatform.fieldMap["platform_id"] = sysUserPlatform.PlatformID
	sysUserPlatform.fieldMap["create_time"] = sysUserPlatform.CreateTime
}

func (sysUserPlatform sysUserPlatform) clone(db *gorm.DB) sysUserPlatform {
	sysUserPlatform.sysUserPlatformDo.ReplaceConnPool(db.Statement.ConnPool)
	return sysUserPlatform
}

func (sysUserPlatform sysUserPlatform) replaceDB(db *gorm.DB) sysUserPlatform {
	sysUserPlatform.sysUserPlatformDo.ReplaceDB(db)
	return sysUserPlatform
}

type sysUserPlatformDo struct{ gen.DO }

func (sysUserPlatform sysUserPlatformDo) Debug() *sysUserPlatformDo {
	return sysUserPlatform.withDO(sysUserPlatform.DO.Debug())
}

func (sysUserPlatform sysUserPlatformDo) WithContext(ctx context.Context) *sysUserPlatformDo {
	return sysUserPlatform.withDO(sysUserPlatform.DO.WithContext(ctx))
}

func (sysUserPlatform sysUserPlatformDo) ReadDB() *sysUserPlatformDo {
	return sysUserPlatform.Clauses(dbresolver.Read)
}

func (sysUserPlatform sysUserPlatformDo) WriteDB() *sysUserPlatformDo {
	return sysUserPlatform.Clauses(dbresolver.Write)
}

func (sysUserPlatform sysUserPlatformDo) Session(config *gorm.Session) *sysUserPlatformDo {
	return sysUserPlatform.withDO(sysUserPlatform.DO.Session(config))
}

func (sysUserPlatform sysUserPlatformDo) Clauses(conds ...clause.Expression) *sysUserPlatformDo {
	return sysUserPlatform.withDO(sysUserPlatform.DO.Clauses(conds...))
}

func (sysUserPlatform sysUserPlatformDo) Returning(value interface{}, columns ...string) *sysUserPlatformDo {
	return sysUserPlatform.withDO(sysUserPlatform.DO.Returning(value, columns...))
}

func (sysUserPlatform sysUserPlatformDo) Not(conds ...gen.Condition) *sysUserPlatformDo {
	return sysUserPlatform.withDO(sysUserPlatform.DO.Not(conds...))
}

func (sysUserPlatform sysUserPlatformDo) Or(conds ...gen.Condition) *sysUserPlatformDo {
	return sysUserPlatform.withDO(sysUserPlatform.DO.Or(conds...))
}

func (sysUserPlatform sysUserPlatformDo) Select(conds ...field.Expr) *sysUserPlatformDo {
	return sysUserPlatform.withDO(sysUserPlatform.DO.Select(conds...))
}

func (sysUserPlatform sysUserPlatformDo) Where(conds ...gen.Condition) *sysUserPlatformDo {
	return sysUserPlatform.withDO(sysUserPlatform.DO.Where(conds...))
}

func (sysUserPlatform sysUserPlatformDo) Order(conds ...field.Expr) *sysUserPlatformDo {
	return sysUserPlatform.withDO(sysUserPlatform.DO.Order(conds...))
}

func (sysUserPlatform sysUserPlatformDo) Distinct(cols ...field.Expr) *sysUserPlatformDo {
	return sysUserPlatform.withDO(sysUserPlatform.DO.Distinct(cols...))
}

func (sysUserPlatform sysUserPlatformDo) Omit(cols ...field.Expr) *sysUserPlatformDo {
	return sysUserPlatform.withDO(sysUserPlatform.DO.Omit(cols...))
}

func (sysUserPlatform sysUserPlatformDo) Join(table schema.Tabler, on ...field.Expr) *sysUserPlatformDo {
	return sysUserPlatform.withDO(sysUserPlatform.DO.Join(table, on...))
}

func (sysUserPlatform sysUserPlatformDo) LeftJoin(table schema.Tabler, on ...field.Expr) *sysUserPlatformDo {
	return sysUserPlatform.withDO(sysUserPlatform.DO.LeftJoin(table, on...))
}

func (sysUserPlatform sysUserPlatformDo) RightJoin(table schema.Tabler, on ...field.Expr) *sysUserPlatformDo {
	return sysUserPlatform.withDO(sysUserPlatform.DO.RightJoin(table, on...))
}

func (sysUserPlatform sysUserPlatformDo) Group(cols ...field.Expr) *sysUserPlatformDo {
	return sysUserPlatform.withDO(sysUserPlatform.DO.Group(cols...))
}

func (sysUserPlatform sysUserPlatformDo) Having(conds ...gen.Condition) *sysUserPlatformDo {
	return sysUserPlatform.withDO(sysUserPlatform.DO.Having(conds...))
}

func (sysUserPlatform sysUserPlatformDo) Limit(limit int) *sysUserPlatformDo {
	return sysUserPlatform.withDO(sysUserPlatform.DO.Limit(limit))
}

func (sysUserPlatform sysUserPlatformDo) Offset(offset int) *sysUserPlatformDo {
	return sysUserPlatform.withDO(sysUserPlatform.DO.Offset(offset))
}

func (sysUserPlatform sysUserPlatformDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *sysUserPlatformDo {
	return sysUserPlatform.withDO(sysUserPlatform.DO.Scopes(funcs...))
}

func (sysUserPlatform sysUserPlatformDo) Unscoped() *sysUserPlatformDo {
	return sysUserPlatform.withDO(sysUserPlatform.DO.Unscoped())
}

func (sysUserPlatform sysUserPlatformDo) Create(values ...*db_model.SysUserPlatform) error {
	if len(values) == 0 {
		return nil
	}
	return sysUserPlatform.DO.Create(values)
}

func (sysUserPlatform sysUserPlatformDo) CreateInBatches(values []*db_model.SysUserPlatform, batchSize int) error {
	return sysUserPlatform.DO.CreateInBatches(values, batchSize)
}

func (sysUserPlatform sysUserPlatformDo) Save(values ...*db_model.SysUserPlatform) error {
	if len(values) == 0 {
		return nil
	}
	return sysUserPlatform.DO.Save(values)
}

func (sysUserPlatform sysUserPlatformDo) First() (*db_model.SysUserPlatform, error) {
	if result, err := sysUserPlatform.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.SysUserPlatform), nil
	}
}

func (sysUserPlatform sysUserPlatformDo) Take() (*db_model.SysUserPlatform, error) {
	if result, err := sysUserPlatform.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.SysUserPlatform), nil
	}
}

func (sysUserPlatform sysUserPlatformDo) Last() (*db_model.SysUserPlatform, error) {
	if result, err := sysUserPlatform.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.SysUserPlatform), nil
	}
}

func (sysUserPlatform sysUserPlatformDo) Find() ([]*db_model.SysUserPlatform, error) {
	result, err := sysUserPlatform.DO.Find()
	return result.([]*db_model.SysUserPlatform), err
}

func (sysUserPlatform sysUserPlatformDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*db_model.SysUserPlatform, err error) {
	buf := make([]*db_model.SysUserPlatform, 0, batchSize)
	err = sysUserPlatform.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (sysUserPlatform sysUserPlatformDo) FindInBatches(result *[]*db_model.SysUserPlatform, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return sysUserPlatform.DO.FindInBatches(result, batchSize, fc)
}

func (sysUserPlatform sysUserPlatformDo) Attrs(attrs ...field.AssignExpr) *sysUserPlatformDo {
	return sysUserPlatform.withDO(sysUserPlatform.DO.Attrs(attrs...))
}

func (sysUserPlatform sysUserPlatformDo) Assign(attrs ...field.AssignExpr) *sysUserPlatformDo {
	return sysUserPlatform.withDO(sysUserPlatform.DO.Assign(attrs...))
}

func (sysUserPlatform sysUserPlatformDo) Joins(fields ...field.RelationField) *sysUserPlatformDo {
	for _, _f := range fields {
		sysUserPlatform = *sysUserPlatform.withDO(sysUserPlatform.DO.Joins(_f))
	}
	return &sysUserPlatform
}

func (sysUserPlatform sysUserPlatformDo) Preload(fields ...field.RelationField) *sysUserPlatformDo {
	for _, _f := range fields {
		sysUserPlatform = *sysUserPlatform.withDO(sysUserPlatform.DO.Preload(_f))
	}
	return &sysUserPlatform
}

func (sysUserPlatform sysUserPlatformDo) FirstOrInit() (*db_model.SysUserPlatform, error) {
	if result, err := sysUserPlatform.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.SysUserPlatform), nil
	}
}

func (sysUserPlatform sysUserPlatformDo) FirstOrCreate() (*db_model.SysUserPlatform, error) {
	if result, err := sysUserPlatform.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.SysUserPlatform), nil
	}
}

func (sysUserPlatform sysUserPlatformDo) FindByPage(offset int, limit int) (result []*db_model.SysUserPlatform, count int64, err error) {
	result, err = sysUserPlatform.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = sysUserPlatform.Offset(-1).Limit(-1).Count()
	return
}

func (sysUserPlatform sysUserPlatformDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = sysUserPlatform.Count()
	if err != nil {
		return
	}

	err = sysUserPlatform.Offset(offset).Limit(limit).Scan(result)
	return
}

func (sysUserPlatform sysUserPlatformDo) Scan(result interface{}) (err error) {
	return sysUserPlatform.DO.Scan(result)
}

func (sysUserPlatform sysUserPlatformDo) Delete(models ...*db_model.SysUserPlatform) (result gen.ResultInfo, err error) {
	return sysUserPlatform.DO.Delete(models)
}

func (sysUserPlatform *sysUserPlatformDo) withDO(do gen.Dao) *sysUserPlatformDo {
	sysUserPlatform.DO = *do.(*gen.DO)
	return sysUserPlatform
}
