// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysPlatform = "sys_platform"

// SysPlatform 平台表
type SysPlatform struct {
	ID         uint64    `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name       string    `gorm:"column:name;not null;comment:平台名称" json:"name"` // 平台名称
	Code       string    `gorm:"column:code;not null;comment:平台编码" json:"code"` // 平台编码
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName SysPlatform's table name
func (*SysPlatform) TableName() string {
	return TableNameSysPlatform
}
