// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameSysPermission = "sys_permission"

// SysPermission 权限表
type SysPermission struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	PlatformID int64     `gorm:"column:platform_id;not null;comment:所属平台ID(sys_platform.id)" json:"platform_id"` // 所属平台ID(sys_platform.id)
	Code       string    `gorm:"column:code;not null;comment:权限编码(menu:<资源> 或 <资源>:<动作>)" json:"code"`           // 权限编码(menu:<资源> 或 <资源>:<动作>)
	Name       string    `gorm:"column:name;not null;comment:权限名称" json:"name"`                                  // 权限名称
	Type       int32     `gorm:"column:type;not null;default:2;comment:类型: 1菜单 2API" json:"type"`                // 类型: 1菜单 2API
	ParentID   *int64    `gorm:"column:parent_id;comment:父权限ID(挂载归属菜单,顶级为NULL)" json:"parent_id"`                // 父权限ID(挂载归属菜单,顶级为NULL)
	Sort       int32     `gorm:"column:sort;not null;comment:同级排序(越小越靠前)" json:"sort"`                           // 同级排序(越小越靠前)
	Status     int32     `gorm:"column:status;not null;default:1;comment:状态: 1启用 0禁用" json:"status"`             // 状态: 1启用 0禁用
	CreatedBy  *int64    `gorm:"column:created_by;comment:创建操作人ID" json:"created_by"`                            // 创建操作人ID
	UpdatedBy  *int64    `gorm:"column:updated_by;comment:最后更新操作人ID" json:"updated_by"`                          // 最后更新操作人ID
	RequestID  *string   `gorm:"column:request_id;comment:最后一次写操作请求ID" json:"request_id"`                        // 最后一次写操作请求ID
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName SysPermission's table name
func (*SysPermission) TableName() string {
	return TableNameSysPermission
}
