// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameSysRole = "sys_role"

// SysRole 角色表
type SysRole struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Code        string    `gorm:"column:code;not null;comment:角色编码(代码引用的稳定标识,不可变)" json:"code"`                                     // 角色编码(代码引用的稳定标识,不可变)
	Name        string    `gorm:"column:name;not null;comment:角色名称(显示用)" json:"name"`                                               // 角色名称(显示用)
	Description *string   `gorm:"column:description;comment:角色描述" json:"description"`                                               // 角色描述
	IsBuiltin   int32     `gorm:"column:is_builtin;not null;comment:内置角色: 1是(admin/hr/manager/employee,不可删除) 0否" json:"is_builtin"` // 内置角色: 1是(admin/hr/manager/employee,不可删除) 0否
	Status      int32     `gorm:"column:status;not null;default:1;comment:状态: 1启用 0禁用(禁用后其授权即时失效)" json:"status"`                   // 状态: 1启用 0禁用(禁用后其授权即时失效)
	CreatedBy   *int64    `gorm:"column:created_by;comment:创建操作人ID" json:"created_by"`                                              // 创建操作人ID
	UpdatedBy   *int64    `gorm:"column:updated_by;comment:最后更新操作人ID" json:"updated_by"`                                            // 最后更新操作人ID
	RequestID   *string   `gorm:"column:request_id;comment:最后一次写操作请求ID" json:"request_id"`                                          // 最后一次写操作请求ID
	CreateTime  time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime  time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName SysRole's table name
func (*SysRole) TableName() string {
	return TableNameSysRole
}
