// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameSysUser = "sys_user"

// SysUser 用户表(管理员+员工)
type SysUser struct {
	ID              int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Account         string    `gorm:"column:account;not null;comment:登录账号" json:"account"`                                  // 登录账号
	Password        string    `gorm:"column:password;not null;comment:密码(bcrypt加密)" json:"password"`                        // 密码(bcrypt加密)
	Name            string    `gorm:"column:name;not null;comment:姓名" json:"name"`                                          // 姓名
	Phone           string    `gorm:"column:phone;not null;comment:手机号" json:"phone"`                                       // 手机号
	Email           string    `gorm:"column:email;not null;comment:邮箱" json:"email"`                                        // 邮箱
	Role            string    `gorm:"column:role;not null;default:employee;comment:角色: admin/employee" json:"role"`         // 角色: admin/employee
	Department      *string   `gorm:"column:department;comment:所属部门" json:"department"`                                     // 所属部门
	PasswordChanged bool      `gorm:"column:password_changed;not null;default:0;comment:是否已修改初始密码" json:"password_changed"` // 是否已修改初始密码
	CreateTime      time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime      time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName SysUser's table name
func (*SysUser) TableName() string {
	return TableNameSysUser
}
